### ISSUE TITLE
TwinDrakeBlade Effect

### ISSUE THREAD

**Issue by RyanTaplin1705** [Suprcode/mir2#14]
Does not broadcast skill effect so that other players can see when they are casting it.

**Comment by Suprcode** [comment]
is it meant to? i was always under the impression tdb graphic was only shown on your own screen.

**Comment by RyanTaplin1705** [comment]
Sorry I come home on Thursday night so haven't been on much. TDB cast graphic should be shown to everyone (seems a little stupid because it's spammable) but I think it's to make people aware that it has been cast.

**Comment by Suprcode** [comment]
issue fixed. tdb now shows on others screen. first time only when it charges so it can't be spammed.
