### ISSUE TITLE
Mirroring doesn't follow master when hitting

### ISSUE THREAD

**Issue by RyanTaplin1705** [Suprcode/mir2#15]
Mirroring clone doesn't move when locked on to a target, it just stands there and tanks the mob which is bad for the players MP. It should follow the player (take one step) then take a hit and then again take one step towards the master and take another hit.

**Comment by RyanTaplin1705** [comment]
Wasn't sure whether to remove the following piece of code:

if (dist >= AttackRange)
    MoveTo(Target.CurrentLocation);

If I left it in then it would probably spaz out and keep moving between the user and the target? Surely it should just keep following the player no matter what (it's not like an ordinary pet).

**Comment by Suprcode** [comment]
has this issue been resolved through the pull request?

**Comment by RyanTaplin1705** [comment]
Yes, just wanted your feedback on the removal of the 

if (dist> AttackRange) 
MoveTo(Target.CurrentLocation);

**Comment by Suprcode** [comment]
great. any new issues with the clone just open a new request
