### ISSUE TITLE
SlashingBurst & MiniMap Update

### ISSUE THREAD

**Issue by RyanTaplin1705** [Suprcode/mir2#17]
After using slashing burst repeatedly it bugs out maps, I've heard that there has been a case of it not loading NPCs if used towards a town then running in town to see no NPCs.

![untitled](https://cloud.githubusercontent.com/assets/11903234/7214850/500f4e80-e5b5-11e4-9102-80ee88557e73.png)

**Comment by Suprcode** [comment]
should no longer have this minimap issue as changed to use the teleport function. however whole spell needs redoing as doesn't work right.
