### ISSUE TITLE
Trainer.

### ISSUE THREAD

**Issue by Pete107** [Suprcode/mir2#188]
As mentioned on LOMCN there is an issue with the Trainer class causing the server to crash if a pet using the SpittingSpider AI or any other that uses Green Poison, there needs to be a check if the attacker is a PlayerObject otherwise the server will try and cast the attacker (in this case MonsterObject) as a PlayerObject.

Here is the post along with the fix:
http://www.lomcn.org/forum/showthread.php?95082-Trainer-Bug-(Crash)&p=1045195#post1045195

**Comment by RyanTaplin1705** [comment]
Pull request #189 has been made. Now just for Far to review and merge if he is happy.
