### ISSUE TITLE
Inventory Position Not Reseting After Using Shop

### ISSUE THREAD

**Issue by RyanTaplin1705** [Suprcode/mir2#196]
Look into code; not sure if there is an exit sequence that can be used to reset position. I assume there is something for shop.visible = false or .hide()

http://www.lomcn.org/forum/showthread.php?94490-an-annoyance-rather-than-a-bug

**Comment by brandc87** [comment]
This will be fixed when I submit my pull request

**Comment by brandc87** [comment]
This is fixed now, can you confirm and close issue. Thanks.
