### ISSUE TITLE
Sabuk wall - wall/gate issues

### ISSUE THREAD

**Issue by RyanTaplin1705** [Suprcode/mir2#198]
http://www.lomcn.org/forum/showthread.php?94665-Afew-Sabuk-Bug

> **Quoted from IceMan** 
>    Seems i could only repair the RightWall. The rest Take your gold with no reapir.

**Comment by RyanTaplin1705** [comment]
@Suprcode 

You commited [81c88d03723a295eb263a5229b5f7698af2077ee](https://github.com/Suprcode/mir2/commit/81c88d03723a295eb263a5229b5f7698af2077ee) which has fixed this issue? Could you verify and closed thread/ issue accordingly.

Thanks

**Comment by CookieLOM** [comment]
This is a duplicate issue can we close this as its already reported
