### ISSUE TITLE
Speedhacks via cheatengine

### ISSUE THREAD

**Issue by RyanTaplin1705** [Suprcode/mir2#20]
Can easily speed hack using cheat engine. Not sure how to put prevention's / checks in place but i'm trying to search up some answers.

**Comment by RyanTaplin1705** [comment]
Seems it might only be an issue with archer?

**Comment by Suprcode** [comment]
most attacks / cooldown timers are client side only - so speed cheating is possible in these parts. i intend to add cooldown timers to every spell server and client side to prevent this eventually.

if the default bow shot is speeding up then there might be a timer check missing server side. will look at this.

**Comment by RyanTaplin1705** [comment]
Ok cool, yeah literually you can use cheatengine 500x speed and kill a mob that may take 10 - 20seconds in 1second with the default bow attack. At higher levels doing thi with bosses etc would be op. I may go through adding a lot of server side timers myself at some point for my server, when I get around to doing them i'll add them on here for you to review and pull.

**Comment by Suprcode** [comment]
the cool down timer's i add will be completely changed compared to how they work now (no manually adding each one in the code) - it'll run from the db. 

Pretty sure i've fixed the attack range speed issue - will check in tonight.

**Comment by RyanTaplin1705** [comment]
Ah nice, you planning on putting the whole of magic in database too then?

Not really necessary for me as I know where to add it but for user usability.
It would be nice to have the delay in one place (e.g. with the icons, spell level etc) but it's a lot more time for me to recode it all to do that then just to add a couple of lines to new spells.

Again for open source friendliness it is probably a good way forward.

**Comment by Suprcode** [comment]
first stage it'll still be hard coded - but eventually it'll all be editable in the db.
