### ISSUE TITLE
FlameAssasin bug.

### ISSUE THREAD

**Issue by Pete107** [Suprcode/mir2#203]
Within the AI it gets the target from a list that is sent through however further through the code of CompleteAttackRange is has an uppercase T rather than the lower case t:

if (Envir.Random.Next(Settings.PoisonResistWeight) >= Target.PoisonResist)
Should be
if (Envir.Random.Next(Settings.PoisonResistWeight) >= target.PoisonResist)

Oh, forgot to mention, this causes the server to crash or at least I assume it was the cause of it, the debug log I got didn't give a line number:

> [10/19/2016 5:32:04 AM] System.NullReferenceException: Object reference not set to an instance of an object.
>    at Server.MirObjects.Monsters.FlameAssassin.CompleteRangeAttack(IList`1 data)
>    at Server.MirObjects.MonsterObject.Process(DelayedAction action)
>    at Server.MirObjects.MapObject.Process()
>    at Server.MirObjects.MonsterObject.Process()
>    at Server.MirEnvir.Envir.ThreadLoop(MobThread Info)

**Comment by RyanTaplin1705** [comment]
Thanks. You could create the commit and push request yourself if you like. 

If not I'll fix it when I'm home. (Y)

**Comment by RyanTaplin1705** [comment]
Nevermind I did it on my phone 😂

**Comment by Pete107** [comment]
My source has far too many changes to be pushing and with it being such a small issue wouldn't really have been worth it :)

**Comment by RyanTaplin1705** [comment]
I have multiple repo's setup on my local and toggle between them. Create a branch make the change and then merge it into my own source and/or master.

**Comment by RyanTaplin1705** [comment]
But I understand. You can also edit directly via github editor. It automatically creates a branch and you can chose to push it.
