### ISSUE TITLE
IC mirror client inject 

### ISSUE THREAD

**Issue by RyanTaplin1705** [Suprcode/mir2#205]
Not a major issue however I was thinking would it be better if using the mirror resets the customName of IC to default name and then if the customName is equal to default name you can then rename it.

Currently it's a client side boolean/button which can be ignored with client manipulation.

Thoughts? @Far

**Comment by Suprcode** [comment]
go for it

**Comment by Suprcode** [comment]
also @ Far doesn't work here - you're including someone else as i dont own github.com/Far lol

I get a notification whenever an issue/comment/commit etc is made

**Comment by RyanTaplin1705** [comment]
Sorry i meant @Suprcode 😂 so confusing

**Comment by Suprcode** [comment]
Theres an error on your commit for the pet name length - you put lower case length instead of Length. Can you fix and commit please

**Comment by RyanTaplin1705** [comment]
My bad; it has been changed and pushed.

**Comment by RyanTaplin1705** [comment]
I can't ever merge from terminal / vs gui. Always get an error related to permissions; how do I do a merge request without getting rejected?

P.S. another error in that same bit of code; missing a semi-colon on the end -_- which i'm trying to push.

**Comment by RyanTaplin1705** [comment]
My implementation is a bit yucky. The change to pet name upon using CreatureMirror e.g. ABC123 -> BabyPig is not instant however the button appearing is (I assume to the tick time of reloading).

Also need to verify and initialise button on load if name is == defaultName. Ahh this rename system is so messy.

**Comment by RyanTaplin1705** [comment]
@Suprcode I don't like this at all, not sure what to do with this. It's very messy. I think there is a better way to implement a rename system (e.g. click and rename instantly) or maybe another way which I can't think of off the top of my head. What are your thoughts on this; i'll revisit it at a later date if I come up with something else or if you have a better solution.

https://github.com/RyanTaplin1705/mir2/tree/IntelligentCreaturebug

**Comment by Suprcode** [comment]
It's a pet renaming item, if you've spent more than 5 minutes looking at it you've looked at it too long. afaik it works fine, and the only issue was the ability to give it a long name (which is now fixed). Move on to something else as there are a million other more important things which need attention.

**Comment by RyanTaplin1705** [comment]
The issue at hand (the one we are discussing in this thread) is the fact that someone can modify the client or create a false packet to rename a pet without actually having a CreatureMirror. I guess it's not a major issue (not game breaking) but non of the less an issue.

I have been trying to work out the best possible solution but it's difficult with the current implementation. Maybe it would have been better to make an NPC command to rename the pet and then create a scripted item (may work out better).

Also have you seen issue #209; this will need attending.

**Comment by Suprcode** [comment]
i wouldn't worry about it - if someone really wants to go to the trouble of hacking the client to rename a pet then the client must be pretty secure in everything else.

As i say, there are a million other issues which need attention, you can't get hung up on something as tiny as this.

**Comment by RyanTaplin1705** [comment]
True; also issue #209 seems to have fixed itself. I'll close #209 and just leave this issue pending; not high priority or an issue at all really.
