### ISSUE TITLE
IC rename issue

### ISSUE THREAD

**Issue by RyanTaplin1705** [Suprcode/mir2#209]
If you rename your pet while it is summoned the rename does not automatically apply.

When you unsummon the pet you can't resummon it ever again. I guess due to a mismatch on names?!

**Comment by Suprcode** [comment]
Just add a check that the creature can't be renamed whilst summoned.

**Comment by RyanTaplin1705** [comment]
Cool thanks, sorry been preoccupied with work and the hackathon i'm attending today.

I will try get petenoobehs fixes in at some point over the weekend depending how full on this hackathon is and I will either look at the bugs (see how major they are) and try to fix or start working on a feature.. Crafting comes to mind but I don't like the current interface so I may design my own so it's like the gameshop but crafting styled. @Suprcode not Far :stuck_out_tongue:
