### ISSUE TITLE
Conquest EndWar.

### ISSUE THREAD

**Issue by Pete107** [Suprcode/mir2#210]
https://github.com/Suprcode/mir2/blob/master/Server/MirObjects/ConquestObject.cs#L370

On that line you have || instead of &&.

**Comment by Pete107** [comment]
My bad, but there is still an issue with that part, really it should only be checking the finish time to the current time, the WarIsOn is fine also.

**Comment by RyanTaplin1705** [comment]
If I'm not mistaken it should be as followes;

Surround start & end in brackets to group them and replace || with &&

```
            if (WarIsOn && (start > now && finish <= now))
            {
                EndWar(Info.Game);
            }
```
