### ISSUE TITLE
Client Graphics: SharpDX! Rework in Progress! (Full Rework).

### ISSUE THREAD

**Issue by Fenrisus** [Suprcode/mir2#218]
Hello there. Managed DirectX has been deprecated for 10 years already, and due to it's age.
Managed DirectX 1.1 as it stands today is deprecated. It was last updated in April 2006 to match that version of D3DX9. The last DirectX SDK to include the samples and documentation for Managed DirectX 1.1 was August 2006.

1)Since the last version of D3DX9 supported by Managed DirectX 1.1 is April 2006, it makes use of a very outdated version of the HLSL compiler.
2)The Managed DirectX 1.1 assemblies are 32-bit only, so you cannot use them from an x64 native .NET application
3)The assemblies only support the legacy DirectX API set, with no support for Direct3D9Ex, Direct3D 10.x, Direct3D 11, Direct2D, DirectWrite, DXGI, D3DX10, D3DX11, XAUDIO2, XACT, XINPUT, etc.
4)Since Managed DirectX 2.0 was never released in production form, the Managed DirectX 1.1 assemblies still reflect .NET 1.1 design principles and does not support or make use of .NET 2.0-4.6 constructs.
5)Managed DirectX 1.1 while compatible with .NET 2.0 (and the .NET 3.0 and .NET 3.5 extensions of the 2.0 runtime), is not compatible with .NET 4.0-4.6

How about replace them with MDX mimic - SlimDX library? That is non hard at general (just some syntax and function names changed if we compare with MDX), and has alot of benefits instead of using 10 years-old deprecated library.

**Comment by Suprcode** [comment]
Thanks for your comments. Yes we're very aware about managed DX's deprecation and limitations, however no one working on the source currently has the time (or knowledge) to update to a more recent engine.

However if you have this time and knowledge please feel free to contribute changes to the source, it would be more than welcome to get the source updated.

**Comment by Fenrisus** [comment]
Well, i can try it. That is not hard at all. Just it has a some kind of "dirty" work, because there is main problem - fight against small & syntax changes. For example, MDX has Direct3D.Manager, but SlimDX nope, and graphics engine initialization going on same way, but with non same syntax.
just for example:
PresentFlag = PresentFlag.LockableBackBuffer,
is
PresentFlags = SlimDX.Direct3D9.PresentFlags.LockableBackBuffer,

or:
if (devCaps.DeviceCaps.SupportsHardwareTransformAndLight)

on SlimDX looks like:
DeviceCaps dc = devCaps.DeviceCaps;
if (dc & DeviceCaps.HWTransformAndLight != 0)

Everything else - seems fine, because there is not so much MDX-specific code at all.

**Comment by RyanTaplin1705** [comment]
Hello, not seen you about before. Did you com from our forum? If so who are you?

@fenrisus

**Comment by Fenrisus** [comment]
I playing Mir long time ago, and also lomcn in my bookmarks, i am just a little indie game developer ;)
And find Mir2 C# & Server remake a very interesting for my own game is not related to Mir, but with using them as Engine. Same tile&sprite based game. 

Well, how it will affect? With SlimDX:
1)You may use new HLSL shaders, and do awesome effects.
2)Better textures drawing (will provide better visual quality)
(right now it's draws a "pixelated" a bit, so, anti-aliasing, linear filters on textures will works like a charm)
3)Better perfomance, especially FPS.
4)Better post processing effects at low costs.
5)No driver/hardware/something else compatibility problems between old PC's (it's still DirectX 9.0c EXT) and new PC's (cuz there is no deprecation) Literally it's like - "try to run DirectX 6.0 application on your Windows 10". Well, foget about it.

Summary: MDX - is **highly** deprecated and shows us their ages nowadays. For example, with SlimDX - you may easy re-compile without any problems client under Xamarin Monodevelop for Linux or MacOS,
but with MDX - no way at all. MDX lack of good & sweet functions for nice-look drawing implemented on Direct3D9Ex. I've found some issues with perfomance also, when you got many monsters / players on screen. That becomes from MDX....

Anyways, i will try to re-write them under SlimDX, and just put it with pull-request. That will be something like fair exchange - i've take Mir2 as Engine for my 2D game, and i will pay back with some improvements for original Mir2 remake ;)

**Comment by RyanTaplin1705** [comment]
Nice, well thanks! You are one of the generous people who actually give back!

Good luck on your implementing SlimDX and with your own project!

**Comment by aolongxue** [comment]
Up!

**Comment by Fenrisus** [comment]
Hello there. Sorry for long time without news, it's just fun project with sporadic development time-to-time. Better look at this:
![mirslimdx](https://cloud.githubusercontent.com/assets/3074538/25066800/dd8fc68c-2239-11e7-96db-ecdf08cdf614.png)

Currently Graphics engine and everything else re-written to SlimDX. Gameplay and etc. untouched and clean.

I'll make a pull request soon as possible.

**Comment by Suprcode** [comment]
sounds great. looking forward to testing it. let me know if you need
anything

**Comment by Fenrisus** [comment]
Okay, i just need configure git, and push everything. and etc. So, little changelog:
DxManager,
MirSprite,
MirImage,
MirControls,
MirScenes,
MirSound - (Fully re-written, using WaveStreams now);
D3D9 Blending params. And alot of another engine-related code. Everything in comments. 

Totally changed 15 files where MDX was defined before, and fully re-writed Sound system to new ones. Old is literally poor. Just look at calling play() at ctor, and what will happens after. Plus usage in code:

```
       public static void PlayMusic(int index, bool loop = false)
        {
            if (Device == null) return;

            Music = new SoundLibrary(index, index + ".wav", true);
            Music.SetVolume(MusicVol);
            Music.Play();
        }
```
And from Ctor:

```
        public SoundLibrary(int index, string fileName, bool loop)
        {
            Index = index;

            fileName = Path.Combine(Settings.SoundPath, fileName);
            if (!File.Exists(fileName)) return;

            _mStream = new MemoryStream(File.ReadAllBytes(fileName));

            _loop = loop;

            _bufferList = new List<SecondaryBuffer>();

            Play();
        }`
```
Playing twice the same thing? 💃 hehe.

Currently everything related is fixed in my code.

**Comment by Fenrisus** [comment]
@Suprcode can you test currently, compiled binaries? Client uploaded to mega:
[https://mega.nz/#!KNBA2L4a!5HI136K9svTR8wugZtcdCLfugz5rWieevvhFL6Lt3JM](url)
I cant test them fully currently, it seems fine, but who knows?

**Comment by Suprcode** [comment]
There are several immediate issues ive noted - such as item hovers show no opacity, and dragging of dialogs only redraws on mouse up. Redrawing seems generally much slower, though on second viewing it seems to cache and speed up.

So theres definately things that need to be looked at before it can be merged in to the main code - but hopefully these are things you're aware of how to fix?

**Comment by Fenrisus** [comment]
yeah, i got already connection to the server. Currently working on fixing them.

**Comment by Suprcode** [comment]
As i say let me know if you need any help - i'm no expert in graphics but keen on getting crystal updated to a newer engine.

**Comment by Fenrisus** [comment]
![332323](https://cloud.githubusercontent.com/assets/3074538/25070701/a779cb9a-22ae-11e7-98d9-955ed7918bc2.png)

Looks good, dragging of dialogs working normaly. 

Working on Resize issues fix, inspired from Disposing & Re-creating Graphics Device and rendering surface.

**Comment by Suprcode** [comment]
great work

**Comment by Suprcode** [comment]
how are you coming on with the other issues @Fenrisus

**Comment by Fenrisus** [comment]
Well, other issues, just inspired from deprecation of events i.e.

```
ControlTexture.Disposing += ControlTexture_Disposing;
Device.DeviceLost += (o, e) => DeviceLost = true;
Device.DeviceResizing += (o, e) => e.Cancel = true;
Device.DeviceReset += (o, e) => LoadTextures();
Device.Disposing += (o, e) => Clean();
```
All those issues, on client what you got, inspired just for "first version" of pure conversion.
Anyways, as you may see it works. (And draws better, currently tested, they draws better, no fps drops).
For current dev, stage, i will re-working DXManager itself for separate some things.
[https://github.com/SlimDX/slimdx/tree/426f59d9e30eaa75cd178f8abdf46ec915530ff7/samples/SampleFramework/Rendering](SlimDX repo - Framework Sample ).
It will looks like this at final. Just declare GraphicsDevice, GraphicsContext, DXManager on right way, and this will be done.

Also i can make a Painter-like system via using Interface, something like:

`IPainter Painter; //DX9, DX10, DX11 selected from options.`

And all drawcalls will be on this way, if needed. Also on long way future, that will provide additional feature: OpenTK or SDL2 renderers are possible. (OpenGL, Angle, Vulcan Device).

Currently, my plan is:

Rework DXManager and Painter graphics device.
Remove deprecated things (Device.DeviceResizing += (o, e) => e.Cancel = true;)
This really too old. 17 years ago, DX Applications does not allow resizing, and that simple disable holding component from resize. Nowadays all DX based applications can be resized without re-launch application itself.
Optimize & Actualize engine resource management. I.e. Textures dispose, reload, chache and etc. 

Finally: Currently i've done investigate all this issues, and that is just rudimentary tails from old ages and code-style. Anyways it's should be replaced first.

**Comment by aolongxue** [comment]
great,nice!

**Comment by Fenrisus** [comment]
Little progress report.
Well, investigating all things is done. Current state:

If we "pure" convert them (just with replace syntax). This is works only for 800x600 resolution.
Change resolution causes **segmentation fault** for Swap Buffers for DirectX Device.
Also, after some time, there is same Device crashes (LostContext, Fails with reset, etc.).
So, after hours of debugging with Intel Graphics Profilers, DirectX SDK (June 10) result is:
Bad draw code inside:
**MirImage
MirControls & UI Generally.**
----------------------------
Solution:

1. Create CrystalMir Framework
2. Migrate MirGraphics, MirLibrary, MirControls, MirSound from client into framework.
3. Rework MirLibrary (MirImage part of code)
4. Rework MirControls - they simple fixed to draw at 800x600 or 1024(with bugs) that is hardcoded.

TODO Implementations:

1. SharpDX (converted already, instead of SlimDX, for example Monogame or Axiom 3D same DX Engine).
2. Texture2D Implementation.
3. Implementation of DXGI; 
4. IRenderer interface. (DX9, DX10, DX11);
5. IDevice interface.(DX9, DX10, DX11);
6. IDrawableObject interface
7. SwapChain - for working with resize and other things.
8. CMain implementation as **class CMain : RenderForm**
9. Implementation of SharpDX RenderLoop (From RederForm);
10. Implementation of CrystalMir Framework small helper things.
11. Implementation of Direct2D draw surface.

Currently i am working on this road. Because "simple migration" is not working for Mir. Both SlimDX and SharpDX has a same behaviour when you simple change resolution (but full screen for example working like a charm). For example:

```
       public MainDialog()
        {
            Index = Settings.Resolution == 800 ? 0 : Settings.Resolution == 1024 ? 1 : 2;
            Library = Libraries.Prguse;
            Location = new Point(((Settings.ScreenWidth / 2) - (Size.Width / 2)), Settings.ScreenHeight - Size.Height);
            PixelDetect = true;
```
As you may see, that is **hardcoded.** Literally resolution cannot be higher than 1024.
But there is another problem - alot of System.Drawing things are implemented. Including Fonts rendering. There is MDX showing their ages, cuz them lack of Direct2D, that useful for drawing UI and
Font things. Deep analysis of code shows me a problem caused by UI drawing through System.Drawing & Font "rendering" inside MirControls. **But** game-scene (i mean character, monsters etc.) working like a charm on any resolution. Just UI give them a serious problems. (Conversions, System.Drawing over actual renderer) and other issues.
 All things starts from:

```
[25.04.2017 6:04:56] SharpDX.SharpDXException: HRESULT: [0x8876086C], Module: [SharpDX.Direct3D9], ApiCode: [D3DERR_INVALIDCALL/InvalidCall], Message: Unknown
   in SharpDX.Result.CheckError()
   in SharpDX.Direct3D9.Device.CreateTexture(Int32 width, Int32 height, Int32 levels, Int32 usage, Format format, Pool pool, Texture textureOut, IntPtr sharedHandleRef)
   in SharpDX.Direct3D9.Texture..ctor(Device device, Int32 width, Int32 height, Int32 levelCount, Usage usage, Format format, Pool pool)
   in Client.MirControls.MirControl.CreateTexture() in M:\SharpDX\mir2-master\Client\MirControls\MirControl.cs:line 149
   in Client.MirControls.MirControl.DrawControl() in M:\SharpDX\mir2-master\Client\MirControls\MirControl.cs:line 726
   in Client.MirControls.MirControl.Draw() in M:\SharpDX\mir2-master\Client\MirControls\MirControl.cs:line 705
   in Client.MirControls.MirControl.DrawChildControls() in M:\SharpDX\mir2-master\Client\MirControls\MirControl.cs:line 744
   in Client.MirControls.MirScene.CreateTexture() in M:\SharpDX\mir2-master\Client\MirControls\MirScene.cs:line 77
   in Client.MirControls.MirControl.DrawControl() in M:\SharpDX\mir2-master\Client\MirControls\MirControl.cs:line 726
   in Client.MirScenes.GameScene.DrawControl() in M:\SharpDX\mir2-master\Client\MirScenes\GameScene.cs:line 831
   in Client.MirControls.MirScene.Draw() in M:\SharpDX\mir2-master\Client\MirControls\MirScene.cs:line 46
   in Client.CMain.RenderEnvironment() in M:\SharpDX\mir2-master\Client\CMain.cs:line 332
[25.04.2017 6:04:56] SharpDX.SharpDXException: HRESULT: [0x8876086C], Module: [SharpDX.Direct3D9], ApiCode: [D3DERR_INVALIDCALL/InvalidCall], Message: Unknown
   in SharpDX.Result.CheckError()
   in SharpDX.Direct3D9.Device.SetRenderTarget(Int32 renderTargetIndex, Surface renderTargetRef)
   in Client.MirGraphics.DXPainter.SetSurface(Surface surface) in M:\SharpDX\mir2-master\Client\MirGraphics\DXPainter.cs:line 218
   in Client.MirScenes.MapControl.CreateTexture() in M:\SharpDX\mir2-master\Client\MirScenes\GameScene.cs:line 8533
   in Client.MirScenes.MapControl.DrawControl() in M:\SharpDX\mir2-master\Client\MirScenes\GameScene.cs:line 8543
   in Client.MirScenes.GameScene.DrawControl() in M:\SharpDX\mir2-master\Client\MirScenes\GameScene.cs:line 829
   in Client.MirControls.MirScene.Draw() in M:\SharpDX\mir2-master\Client\MirControls\MirScene.cs:line 46
   in Client.CMain.RenderEnvironment() in M:\SharpDX\mir2-master\Client\CMain.cs:line 332
[25.04.2017 6:04:56] SharpDX.SharpDXException: HRESULT: [0x8876086C], Module: [SharpDX.Direct3D9], ApiCode: [D3DERR_INVALIDCALL/InvalidCall], Message: Unknown
   in SharpDX.Result.CheckError()
   in SharpDX.Direct3D9.Device.SetRenderTarget(Int32 renderTargetIndex, Surface renderTargetRef)
   in Client.MirGraphics.DXPainter.SetSurface(Surface surface) in M:\SharpDX\mir2-master\Client\MirGraphics\DXPainter.cs:line 218
   in Client.MirScenes.MapControl.CreateTexture() in M:\SharpDX\mir2-master\Client\MirScenes\GameScene.cs:line 8533
   in Client.MirScenes.MapControl.DrawControl() in M:\SharpDX\mir2-master\Client\MirScenes\GameScene.cs:line 8543
   in Client.MirScenes.GameScene.DrawControl() in M:\SharpDX\mir2-master\Client\MirScenes\GameScene.cs:line 829
   in Client.MirControls.MirScene.Draw() in M:\SharpDX\mir2-master\Client\MirControls\MirScene.cs:line 46
   in Client.CMain.RenderEnvironment() in M:\SharpDX\mir2-master\Client\CMain.cs:line 332
```
And this is **never** happens while you playing with 800x600. And this things **never** happens at application/game itself startup. Just play it 3-5 min. And they will appears with that style.
Well, there is no simple way to do that. But let's start to rework them on the right way.

**Comment by aolongxue** [comment]
Look forward to your pull

**Comment by w43869121** [comment]
@Fenrisus  Did you finish? Did not see you make new progress!

**Comment by Chris-Glass** [comment]
@Fenrisus very interested in your progression on this? If you are no longer developing this, would you consider releasing what you have done so far so that others can look to complete?

**Comment by Fenrisus** [comment]
I did both versions SharpDX and SlimDX. Found issues and some fixes. Just need to update them to current (latest) ver. of the trunk. + I'm still test them.

Mono? Since there is Net.Core i guess them deprecated and just "legacy". But override them to Net.Core requires at lest platform & windows API based code rework.

**Comment by Chris-Glass** [comment]
Hey @Fenrisus - do you still intend to release this? Really eager to have a look what you've done!

Been holding off taking on this task, hoping you would give me a nice head start hah.

Thanks bud.

**Comment by Fenrisus** [comment]
> 
> 
> Hey @Fenrisus - do you still intend to release this? Really eager to have a look what you've done!
> 
> Been holding off taking on this task, hoping you would give me a nice head start hah.
> 
> Thanks bud.

Yeah, i will release it very soon

**Comment by suixin567** [comment]
@Fenrisus  thanks ！ We are looking forward to it

**Comment by kthxbye999** [comment]
Hey @Fenrisus 

Any update on this yet? 

could you upload what you have done currently? maybe i can fork and finish it off ? 


Thanks

**Comment by Chris-Glass** [comment]
@Fenrisus any news on this? Been eagerly awaiting hah, thanks bud.

**Comment by CookieLOM** [comment]
Yeah would be good to hear the progress



Sent from my Samsung Galaxy smartphone.

-------- Original message --------

**Comment by suixin567** [comment]
@Fenrisus  half of users will black screen ，so we are very very need a new engine! thanks very much!

**Comment by SpecimenLove** [comment]
@Fenrisus can you please share the work you have done on this? It would be greatly appreciated!

**Comment by WithAnOrchid** [comment]
any updates?

**Comment by Suprcode** [comment]
This was originally opened in 2016. I think it should be obvious nothing is getting released.

Should the @Fenrisus decide to provide a release for this it can be reopened.
