### ISSUE TITLE
Hydra AI

### ISSUE THREAD

**Issue by RyanTaplin1705** [Suprcode/mir2#219]
Hydra AI is broken.

Either it needs to be stationary and spit things or it needs an animation to go under ground, move then reappear. I'm not sure which it should be but will find out when I get to it.

http://www.lomcn.org/forum/showthread.php?94849-Brief-Updates-On-Fix-s-(ingame)

**Comment by Suprcode** [comment]
Hydrax AI isn't broken, its just not coded. His confusion is because it has an image given (as does every monster ) but it flashes. This is because the frames it has isn't compatible with the basic AI of 0.

**Comment by RyanTaplin1705** [comment]
Ah you can close that thread then, i guess we just bundle this issue with the other monster AI's what haven't yet been completed either.
