### ISSUE TITLE
Server Crash Log

### ISSUE THREAD

**Issue by RyanTaplin1705** [Suprcode/mir2#220]
```
[14/11/2016 02:40:55] System.NullReferenceException: Object reference not set to an instance of an object.
at Server.MirNetwork.MirConnection.Process()
at Server.MirEnvir.Envir.WorkLoop() at line 0
```

Very vague, from [Incredulous](http://www.lomcn.org/forum/member.php?28634-Incredulous). I was looking into the .Process() methods and found the below code.

I'm wondering if the client does not exist or is not connected why are we disconnecting them? Shouldn't be the opposite? If they are connect & do exist then disconnect them. @Suprcode 

```
if (_client == null || !_client.Connected)
{
                Disconnect(20);
                return;
}
```

**Comment by RyanTaplin1705** [comment]
If you then step into **Disconnect(20)** it then does the following which contradicts the previously piece of code? 

e.g. if !Connected do Disconnect -> if !Connected return; 

[code]
public void Disconnect(byte reason)
        {
            if (!Connected) return;
[/code]

**Comment by Suprcode** [comment]
Disconnect method is cleaning up the server connection - the client.connected is the client connection

So once the client disconnects, the server needs to clean everything up and disconnect it from the server end.

**Comment by RyanTaplin1705** [comment]
So if client connection is null or disconnected then disconnect the server side socket for that client?

**Comment by RyanTaplin1705** [comment]
Do you think adding the null checks will possibly prevent this? Although should it ever get to this point where they are null and still in the list?

```
lock (Connections)
                            {
                                for (int i = Connections.Count - 1; i >= 0; i--)
                                {
                                    **if (Connections[i] != null)**
                                        Connections[i].Process();
                                }
                            }

                            lock (StatusConnections)
                            {
                                for (int i = StatusConnections.Count - 1; i >= 0; i--)
                                {
                                    **if (StatusConnections[i] != null)**
                                        StatusConnections[i].Process();
                                }
                            }
```

**Comment by Suprcode** [comment]
i expect adding null checks is just hiding the real issue. and i dont know
enough about the issue to suggest how to fix it

**Comment by RyanTaplin1705** [comment]
Hmm the real issue, but what does that entail? The real issue at hand (i assume) is that it's trying to run .Process() on Connection that is null?

So maybe trying to look for where connections are set to null and work around that may be a better solution? However do you know if this .Process() can be running synchronously alongside other method calls? E.g. a method is being run that is setting the connection to null whilst the method to run .Process() is also running.

Maybe i'll ask Jamie if he's feeling generous enough to give me some info/tips 😃 thanks @Suprcode

**Comment by Suprcode** [comment]
i think you mean async, and no the server workloop runs on a single thread
so can only be called 1 at a time

**Comment by RyanTaplin1705** [comment]
After falling asleep and checking my PMs there was little progress. Jamie is unsure of the issue aswell however has given some pointers;

> Possible causes: 
> 1. Either Multiple Threads are calling Process() at the same time.
> 2. SMain.Envir is null
> 
> I can't be certain if the MirConnection is Null or there is a variable inside the Process() Method is null because the "at line 0" seems to be throwing me off.

So going forward from here; possibly add a null check within the loop as I have done above alongside some server side logging/debugging so we can check if we ever get into a state were we receive a null Connection which it is trying to process. We can then see if this temporarily / permanently fixes the issue. Otherwise I'm not sure where to go forward; any other suggestions?

**Comment by RyanTaplin1705** [comment]
@Suprcode are you sure it's not asynchronous? In the config.ini there is settings for more than one thread. Which is also reflected in the WorkLoop() method which is where we are getting the error. I think it's only for monsters.

I don't think this is related though; it is within WorkLoop() but it's around .Process()

```
MobThread Info = MobThreads[j];
                        if (j > 0) //dont start up 0 
                        {
                            MobThreading[j] = new Thread(() => ThreadLoop(Info));
                            MobThreading[j].IsBackground = true;
                            MobThreading[j].Start();
                        }
```

```
Multithreaded=True
ThreadLimit=2
```

**Comment by Suprcode** [comment]
threading is used purely on monsters, everything else running on the same thread

**Comment by RyanTaplin1705** [comment]
I've added a bunch of logging in a separate branch around WorkLoop() and all Process() method calls I could find in it. I'll ask the NoName server gm to implement it and send me the log file when the server crashes to see if it catches any nulls anywhere.

**Comment by RyanTaplin1705** [comment]
Is it normal that we are running Process() on a tonne of empty maps?

P.S. the log is wrong it's at MirEnvir.Envir
```
15/11/2016 21:32:00: MapList[i] where i = 373 was null [Line 628 MirNetwork.MirConnection]
15/11/2016 21:32:00: MapList[i] where i = 374 was null [Line 628 MirNetwork.MirConnection]
15/11/2016 21:32:00: MapList[i] where i = 375 was null [Line 628 MirNetwork.MirConnection]
15/11/2016 21:32:00: MapList[i] where i = 376 was null [Line 628 MirNetwork.MirConnection]
15/11/2016 21:32:00: MapList[i] where i = 377 was null [Line 628 MirNetwork.MirConnection]
15/11/2016 21:32:00: MapList[i] where i = 378 was null [Line 628 MirNetwork.MirConnection]
15/11/2016 21:32:00: MapList[i] where i = 379 was null [Line 628 MirNetwork.MirConnection]
15/11/2016 21:32:00: MapList[i] where i = 380 was null [Line 628 MirNetwork.MirConnection]
15/11/2016 21:32:00: MapList[i] where i = 381 was null [Line 628 MirNetwork.MirConnection]
15/11/2016 21:32:00: MapList[i] where i = 382 was null [Line 628 MirNetwork.MirConnection]
15/11/2016 21:32:00: MapList[i] where i = 383 was null [Line 628 MirNetwork.MirConnection]
15/11/2016 21:32:00: MapList[i] where i = 384 was null [Line 628 MirNetwork.MirConnection]
15/11/2016 21:32:00: MapList[i] where i = 385 was null [Line 628 MirNetwork.MirConnection]
15/11/2016 21:32:00: MapList[i] where i = 0 was null [Line 628 MirNetwork.MirConnection]
15/11/2016 21:32:00: MapList[i] where i = 1 was null [Line 628 MirNetwork.MirConnection]
15/11/2016 21:32:00: MapList[i] where i = 2 was null [Line 628 MirNetwork.MirConnection]
15/11/2016 21:32:00: MapList[i] where i = 3 was null [Line 628 MirNetwork.MirConnection]
15/11/2016 21:32:00: MapList[i] where i = 4 was null [Line 628 MirNetwork.MirConnection]
```

**Comment by Suprcode** [comment]
empty maps still have to processed like everything else. there are already
checks in the suitable methods to skip over parts which dont need to run
when empty

**Comment by RyanTaplin1705** [comment]
So doing the lightning / lava effects on an empty map is necessary? I find it odd a little. 

I'm not sure if my understanding of 'an empty map' correct. I thought an empty map would be a Map that has no file associated to it or something along those lines.

**Comment by Suprcode** [comment]
things like lava effects take little to no processing time. only the main
processes are paused on empty maps.

if a map has no file then it wont be loaded at all i expect. empty maps are
those with no players.

**Comment by RyanTaplin1705** [comment]
Hmm interesting; so how is that defined? I assume when Map = null it would mean all of the following fields are undefined. Not just players.

It's kind of like saying that Object Car = null; means it has no people in the car when in fact I read it as - Car does not exist (there is no car). How do you come to this conclusion? Sorry if it's a noob question 😭 


```
        public MapInfo Info;
        public int Thread = 0;

        public int Width, Height;
        public Cell[,] Cells;
        public List<Point> WalkableCells;
        public Door[,] DoorIndex;
        public List<Door> Doors = new List<Door>();
        public MineSpot[,] Mine;
        public long LightningTime, FireTime, InactiveTime;
        public int MonsterCount, InactiveCount;

        public List<NPCObject> NPCs = new List<NPCObject>();
        public List<PlayerObject> Players = new List<PlayerObject>();
        public List<MapRespawn> Respawns = new List<MapRespawn>();
        public List<DelayedAction> ActionList = new List<DelayedAction>();

        public List<ConquestObject> Conquest = new List<ConquestObject>();
        public ConquestObject tempConquest;
```

**Comment by Suprcode** [comment]
ive no idea what you mean. if the map file doesnt exist the map object wont
get created.

**Comment by RyanTaplin1705** [comment]
So let me break down my thoughts. Maybe there is some miscommunication; i'm sure this will sound really patronizing however I hope it will make it a bit clearer,

**MapList is defined here as a List of Map Objects**
`public List<Map> MapList = new List<Map>();`

**So MapList[i] is an instance of Map Object**
`MapList[i] = Map Object`

**If MapList[i] = null then we have a null/ non existant Map Object. So we shouldn't have any of these but for some reason we do?**
`MapList[i] = null <- Means that the mapObject is non existant?`

**Comment by Suprcode** [comment]
map should never be null. not sure how it would even be possible since its
only added to the list after an instance is created

**Comment by RyanTaplin1705** [comment]
Hmm i'm not sure either; the only instances of MapList.Add(map) i found are as follows.

```
            Map map = new Map(this);

            if (!map.Load()) return;

            SMain.Envir.MapList.Add(map);
```

I assume the !map.Load() should catch any errors; if thhe map is null it shouldn't allow map.Load() to run on it anyway. Not really familiar with try { } catch { } so couldn't tell if it's working as intended.

**Comment by Suprcode** [comment]
id double check your debugging. map cannot be null and in the maplist

**Comment by RyanTaplin1705** [comment]
```
for (int i = 0; i < MapList.Count; i++)
                        {
                            //File.AppendAllText(@".\DebuggingError.txt", String.Format("{0}: MapList[i] where i = {1} was null [Line 628 MirNetwork.MirConnection]", DateTime.Now, i) + Environment.NewLine);
                            MapList[i].Process();
                        }
```

Lols dumbo me; I think someone forgot to put the if() statement in 🤓 👊 

Sorry. I'm being stupid today 😢

**Comment by RyanTaplin1705** [comment]
Doesn't seem to have happened for a while. I'll close the issue; if it reoccurs I can reopen it.
