### ISSUE TITLE
CONQUESTWALL Command not working

### ISSUE THREAD

**Issue by RyanTaplin1705** [Suprcode/mir2#224]
Only works on one wall (left) and not any others as reported in various threads.

**Comment by CookieLOM** [comment]
I did fix this but for life of me still haven't worked out how to submit the fix as my code is in a private repo so its not linked to the public one :confused:

**Comment by Suprcode** [comment]
is this fixed? @daneo1989  ?

**Comment by CookieLOM** [comment]
I did the code to fix it but dunno how to submit it lol



Sent from my Samsung Galaxy smartphone.

-------- Original message --------

**Comment by daneo1989** [comment]
Was this the fix to respawn the Walls? I did add the fix which Cookie provided, Need to double check

**Comment by Suprcode** [comment]
yes it was only the first wall being spawnable bug

**Comment by daneo1989** [comment]
Yes mate, https://github.com/Suprcode/mir2/pull/246/commits
