### ISSUE TITLE
freezing not working on items

### ISSUE THREAD

**Issue by Suprcode** [Suprcode/mir2#24]
freezing effect on items cause purple on mobs but no slow on their movement/attack speed

**Comment by RyanTaplin1705** [comment]
Did you fix the attack on players? I can't remember if I looked into this or not but it has to be programmed differently to the players (possibly reducing their frame and walk speed while slowed might work) but just slowing their frame speed causes them to hit you when your not near them.

**Comment by Suprcode** [comment]
no i've not changed the frame speeds yet on players for attacking, only movement

**Comment by RyanTaplin1705** [comment]
Just read that over again, I was referring to the monsters in the second half (e.g. being hit when they aren't near you) if you try to apply a similar slow effect to monsters.

**Comment by Suprcode** [comment]
no i don't see a need to apply slow frames to monsters - we can control their slowness by walk wait and attack wait. Only reason theres more of a need to do this on players is because having a walk-wait for players will be annoying

**Comment by RyanTaplin1705** [comment]
But the issue here is that if you just slow down the walk wait / attackwait the monster will look stupid - moving to their next space fast and attacking fast. I think you need to add a combination of both so that the walkwait/attackwait are in combination with the frame speed change.
