### ISSUE TITLE
Game Caton

### ISSUE THREAD

**Issue by EssenRoc** [Suprcode/mir2#257]
I do not know why press the 'F10' game will be Caton.
Do you have such a situation?
Thank you

**Comment by daneo1989** [comment]
Sorry can you provide a bit more information and possibly screenshots of the issue?

Sorry for my ignorance whats a Game Caton?

**Comment by EssenRoc** [comment]
When F10 is pressed, the entire screen is stuck

**Comment by EssenRoc** [comment]
Maybe it's my problem

**Comment by daneo1989** [comment]
I have only noticed the screen to freeze when you try using Awakening with incorrect Script. I have not come across the screen crashing when trying to use F10, Have you changed anything within the code which might cause this issue?

**Comment by EssenRoc** [comment]
I changed the CMain.ControlBox to false.

**Comment by Suprcode** [comment]
http://www.lomcn.org/forum/showthread.php?97392-Weird-lag-bug-from-useing-a-f-key&highlight=controlbox

**Comment by EssenRoc** [comment]
@Suprcode Is there any other solution?

**Comment by Suprcode** [comment]
Having Controlbox = false should sort the issue, if it's already false not sure why it's still happening

**Comment by EssenRoc** [comment]
the issue occurred in ControlBox = ture
