### ISSUE TITLE
Poison steals last hitter

### ISSUE THREAD

**Issue by Suprcode** [Suprcode/mir2#27]
green psn on boss moves the last hitter on tao , like a grp of players on my svr were doing a boss , tao comes on last second and steals boss with green psn

**Comment by RyanTaplin1705** [comment]
Possibly make poison only assign last hitter on initial cast rather than every tick?

**Comment by Suprcode** [comment]
only just got around to looking at this. the code already has this check in place - so if someone already is "EXPOwner" no one else can take it. The exp owner must be attacking the monster constantly (atleast once every 5 seconds)

--

poison code to confirm below.

if (EXPOwner == null || EXPOwner.Dead)
                        {
                            EXPOwner = poison.Owner;
                            EXPOwnerTime = Envir.Time + EXPOwnerDelay;
                        }
                        else if (EXPOwner == poison.Owner)
                            EXPOwnerTime = Envir.Time + EXPOwnerDelay;
