### ISSUE TITLE
What is the font name of the Client?

### ISSUE THREAD

**Issue by ryancheung** [Suprcode/mir2#275]
![mir_cap](https://user-images.githubusercontent.com/240899/37262351-8f07298a-25dd-11e8-8a91-84ab8ad0f00b.png)

Could you tell me the font (Number `0` is showing a rectangle, and so is character `O`), please?

**Comment by daneo1989** [comment]
Please, can you point out in the screenshot, I cannot see anything

**Comment by ryancheung** [comment]
![image](https://user-images.githubusercontent.com/240899/37327873-f0289aa0-26d2-11e8-8d4c-c65e7c8eea3d.png)
e.g.  What is the font of the test in the image above?

**Comment by Suprcode** [comment]
You have the source directly available to you.

Settings.cs

public static string FontName = "Tahoma";

Should come default with Windows
