### ISSUE TITLE
Purchase Item List,

### ISSUE THREAD

**Issue by daneo1989** [Suprcode/mir2#277]
When you try to purchase items via Pearls it brings up the craft dialog.

**Comment by yam3842377** [comment]
in ServerPackets.cs
find `public sealed class NPCPearlGoods : Packet`
add `public PanelType Type;`
in `protected override void ReadPacket(BinaryReader reader)`
add `Type = (PanelType)reader.ReadByte();`
in `protected override void WritePacket(BinaryWriter writer)`
add `writer.Write((byte)Type);`

in Server/MirObjects/NPCobject.cs
find `case PearlBuyKey:`
`player.Enqueue(new S.NPCPearlGoods { List = Goods, Rate = PriceRate(player) });`
change to 
`player.Enqueue(new S.NPCPearlGoods { List = Goods, Rate = PriceRate(player), Type = PanelType.Buy });`

in Client/MirScenes/GameScene.cs
find `private void NPCPearlGoods(S.NPCPearlGoods p)`
add `NPCGoodsDialog.UpdatePanelType(p.Type);`
