### ISSUE TITLE
Red Poison

### ISSUE THREAD

**Issue by Suprcode** [Suprcode/mir2#31]
Red poison doesn't currently do anything. The poison code is added, however there is no defence reduction code added that i can see

**Comment by RyanTaplin1705** [comment]
armour = (int)(armour * PoisonRate);

             case PoisonType.Red:
                        PoisonRate -= 0.5F;
                        break;

**Comment by Suprcode** [comment]
hmm. that does reduce your armour - however for players it's backwards

case PoisonType.Red:
                        PoisonRate += 0.10F;
                        break;

so when players are red poisoned their armour will increase.

also it's also set to affect your health reduction amount

if (amount < 0) amount = (int)(amount * PoisonRate);

not sure if these are correct?

**Comment by RyanTaplin1705** [comment]
Ah I didn't check for both players & monsters but you could just make it so in the players itchanges to += 0.10F by making a new case statement or just doing (armour * (PoisonRate * PoisonRate)). Two negatives will make it a positive.

**Comment by Suprcode** [comment]
not like that it doesn't - 0.9 * 0.9 = 0.081

it would need to be 0.9 * -1 if you're doing it that way.

but i've just changed it so it doesn't affect the hp amount anymore, and instead reduces armour like it does on monsters.
