### ISSUE TITLE
Is there a prebuilt release that i can try it out?

### ISSUE THREAD

**Issue by shellohunter** [Suprcode/mir2#32]
Is there a prebuilt release that i can try it out?

Sorry that  I have to post my question here because somehow I cannot access lomcn recently.
I am a big fans of Mir2, and I am excited to find this project. I'd like to see what's in it and what it looks like now, but I am not familiar with C#, I tried to build the project myself but failed at the client part...

**Comment by Suprcode** [comment]
you must compile the project yourself - i do not provide any binary files.

all client files and guides can be found on lomcn
