### ISSUE TITLE
Build errors!!!

### ISSUE THREAD

**Issue by suixin567** [Suprcode/mir2#321]
@Suprcode  @Pete107 
1、MonsterObject and PlayerObject are both in build errors now , Even I click download zip button get a new project, is still does not work. This error caused maybe from Pete107 committed 2 days ago about  "Fatal Sword Leveling fix" .  and I am sure about this error.
2、How to write a robot script in 00Robot.txt? I want to write some timed task in game . could you give me a sample example? thank...

**Comment by Pete107** [comment]
Would be helpful if you could provide the line number of the error when you try and build, the robot built in doesn’t do anything as mentioned on LOMCN.

**Comment by suixin567** [comment]
@Pete107
MonsterObject.cs  .about at  line 2100.  You can download the project zip ,and the errors will appear.  And i thank robot script is useful，if it does not implement, what can I do to instead of to write a timed task? Thank you.

**Comment by Pete107** [comment]
I've just downloaded a fresh copy of the .zip and had no build issues.

> ========== Build: 1 succeeded, 0 failed, 0 up-to-date, 0 skipped ==========

**Comment by suixin567** [comment]
please try to build the server project.



------------------ 原始邮件 ------------------
发件人: "Pete107"<notifications@github.com>;
发送时间: 2019年5月30日(星期四) 下午3:24
收件人: "Suprcode/mir2"<mir2@noreply.github.com>;
抄送: "/shd"<591821945@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [Suprcode/mir2] Build errors!!! (#321)



I've just downloaded a fresh copy of the .zip and had no build issues.
  ========== Build: 1 succeeded, 0 failed, 0 up-to-date, 0 skipped ==========

**Comment by Pete107** [comment]
I did and it built fine.

http://grabilla.com/0951e-b3921ec9-dc78-4ba2-a178-9685f78ecd7d.html
http://grabilla.com/0951e-e90c9944-a8ec-4798-a55d-3c4081d5ec4e.html

Regards to robot you need to do the logic for processing the NPC and the specified times, I didn't follow the original base of the Robot (I found it easier to build my own based on the needs put to me)

**Comment by suixin567** [comment]
@Pete107  
I see!  it is a syntax rules.
your syntax is :    var armour = GetArmour(type, attacker, out bool hit); 
and it will appear errors
please change it to :
bool hit;
 var armour = GetArmour(type, attacker, out hit); 
the errors will disappear.
if you dose not want to make this change ,please tell me want can I do to resolve this problem. thanks!
I have tried whith both c#4 and c#6 ,both does not work.

**Comment by Pete107** [comment]
This is what mine is set to (not quite sure which version it is like but it's always been the default for me)
http://grabilla.com/0951e-a48eafe9-2ee1-402f-a18b-cd20a5742b5d.html

Also using VisualStudio Community 2019.

**Comment by Suprcode** [comment]
I have no build errors either. "out bool hit" is valid syntax for the latest c# versions.

**Comment by suixin567** [comment]
thanks. my setting is same with you.
however , I think a more compatible way of writing is friendly. you just  need a little change.
1、MonsterObject.cs at line 2073
2、PlayerObject.cs at line 10095
if you do not change , my vs2015 will can not work... please! 





------------------ 原始邮件 ------------------
发件人: "Pete107"<notifications@github.com>;
发送时间: 2019年5月30日(星期四) 下午3:57
收件人: "Suprcode/mir2"<mir2@noreply.github.com>;
抄送: "/shd"<591821945@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [Suprcode/mir2] Build errors!!! (#321)



This is what mine is set to (not quite sure which version it is like but it's always been the default for me)
 http://grabilla.com/0951e-a48eafe9-2ee1-402f-a18b-cd20a5742b5d.html
 Also using VisualStudio Community 2019.

**Comment by suixin567** [comment]
@Pete107 @Suprcode

**Comment by Suprcode** [comment]
Can't you update to vs2019? It's valid syntax, so we can't not use the newer techniques just to retain compatibility with old visual studio.

I'm very surprised your code has compiled up until now, as many other things should have been using new c# code styles.

**Comment by Pete107** [comment]
You need to update the C# version to 7.0 or above. (I suggest updating the Visual Studio version you have installed)

If you really don't want to update..
A quick google search found this mentioning downloading the nuget package.
https://stackoverflow.com/questions/39461407/how-to-use-c-sharp-7-with-visual-studio-2015

However by doing so you may cause issues for others unless you add the changes made to the ignore list (providing it's not required), but I think it's still better to update the VS version, there's a lot of changes which help shorten down code.

**Comment by suixin567** [comment]
@Suprcode @Suprcode   I think this error is not my fault, because both my work computer and home computer all appear this error.   and so many people do not use vs2019 , This can cause problems for other people,and for some reasons , It's really inconvenient to update vs studio.  and the error just in out syntax. I still think make a change is good.

**Comment by Pete107** [comment]
C# 7.0 was first introduced in VisualStudio 2017 if I'm not mistaken, really the whole code should be refactored into using the shorter syntax, it's usually best practice to learn the newer syntax to aid you further in development.

Shortening code down is wonderful to do and makes it a whole lot cleaner, I do suggest you update to at least VS 2017.

**Comment by suixin567** [comment]
@Pete107  haha thanks !  I'll have to listen to you. I just worried  other peoples. all right !

**Comment by Suprcode** [comment]
People need to keep up to date with the latest changes. Software will never move forward if we refuse to update.
