### ISSUE TITLE
Act command :  GetRandomText   

### ISSUE THREAD

**Issue by suixin567** [Suprcode/mir2#324]
@Suprcode 
I want to write a new act command : GetRandomText     
usage: 
#ACT 
GETRANDOMTEXT xxx.txt A10
purpose:
get a random line in xxx.txt and assignment to A10
this will useful for get a random value when write a script

how do you think this? or is there a similar command allready exist?

**Comment by Suprcode** [comment]
Theres nothing currently which can do this in a single command. So yes sounds useful to me.

**Comment by suixin567** [comment]
@Suprcode  ok , I will do this command soon .
