### ISSUE TITLE
HwanDevil Set - resets BagWeight

### ISSUE THREAD

**Issue by RyanTaplin1705** [Suprcode/mir2#34]
When you equip 2 pieces of HwanDevil set it resets your bagweight to 255 if over 255 (e.g. 2000 to 255).

**Comment by RyanTaplin1705** [comment]
Every one of these
MaxBagWeight = (byte)Math.Min(byte.MaxValue, MaxBagWeight + 20);
needs to be changed
MaxBagWeight = (ushort)Math.Min(ushort.MaxValue, MaxBagWeight + 20);

**Comment by ToddMcnoltyZ4** [comment]
It appears that equipping two pieces of the HwanDevil set triggers a bag weight reset, which resets your bag weight to 255 if it was previously over 255. For example, if your bag weight was 2000, it would be reset to 255 upon equipping the two pieces of the set.
