### ISSUE TITLE
Possibly use BinaryFormatter

### ISSUE THREAD

**Issue by damianday** [Suprcode/mir2#358]
BinaryReader and Writer are used all over the place for packets, the implementations could probably be made far simpler, easier  to extend and less risk of introducing bugs using serialization, at the cost of larger packets and slower processing, but in reality I doubt these two issues would be costly.

**Comment by Suprcode** [comment]
There are many things which the crystal files would benefit from, however development has stopped with no one contributing to further changes.

Feel free to create pull requests which can then be reviewed and discussed should you wish to contribute any improvements. If you'd just like to discuss what can be changed i'd recommend doing this over at LOMCN where it will be seen with greater visibility.
