### ISSUE TITLE
Consider porting to a better framework

### ISSUE THREAD

**Issue by damianday** [Suprcode/mir2#359]
Managed DirectX is ancient I'm sure you already know the issues with it so I won't drag them up.

But their are plenty of new frameworks such as sfml2, raylib, monogame, sdl2, allegro5 any of these would be an improvement and allow the client to be cross platform.

**Comment by Suprcode** [comment]
These are already in discussion over at LOMCN. Any contributions to port the files over to a better framework is welcome.
