### ISSUE TITLE
Hiding (object transparency) bug

### ISSUE THREAD

**Issue by RyanTaplin1705** [Suprcode/mir2#36]
If a player has a level effect it stops their hiding effect from showing.

Also hiding isn't working on SummonHolyDeva, it stops monsters from seeing it but the transparency on both the casters and other players screen doesn't appear.

![untitled](https://cloud.githubusercontent.com/assets/11903234/7667640/b2eb0bc6-fc07-11e4-9ead-572441b471f7.png)

![untitled](https://cloud.githubusercontent.com/assets/11903234/7667647/1af538d6-fc08-11e4-839e-23fb67520131.png)

**Comment by Suprcode** [comment]
transparency on players should be fixed now. I just stopped drawing the level effect when hidden and it seemed to resolve the issue.

haven't looked at devas but i expect its the same cause with their wing effect

**Comment by RyanTaplin1705** [comment]
:+1: nice job, I put the patch in and it seems to be working nicely as you said.

**Comment by Suprcode** [comment]
might need to redo. not happy that i'm excluding effects when hidden. Not sure what official does but i expect it just draws the effects with transparency too.

**Comment by RyanTaplin1705** [comment]
Yeah I think so too (especially things like mir wings, omakingrobe effect etc).

**Comment by Suprcode** [comment]
fixed this issue. effects now show again and transparency works.
