### ISSUE TITLE
Spell Poison on hit

### ISSUE THREAD

**Issue by RyanTaplin1705** [Suprcode/mir2#37]
Shouldn't the poison check in the attacked method be as follows? Currently spells that shouldn't green poison are green poisoning e.g. soulfireball, fireball etc. It needs to be done in monster and player if you decide to change it.

if (attacker.PoisonAttack > 0 )
if (attacker.PoisonAttack > 0 && type != DefenceType.MAC && type != DefenceType.MACAgility)

**Comment by Suprcode** [comment]
why shouldn't they be green poisoning? surely if you have a poison attack stat - then all of your attacks should be providing poison?

**Comment by RyanTaplin1705** [comment]
As far as I know poison / slow only worked melee hits, it also enhanced poison / slow based spells like frost crunch and poisonsword. Changed it on my source anyway :)

**Comment by Suprcode** [comment]
this is now fixed
