### ISSUE TITLE
LibEditor covert big Wil file error

### ISSUE THREAD

**Issue by feitenging** [Suprcode/mir2#371]
CreateTexture()
 Bytes array out of index
covert false

**Comment by Suprcode** [comment]
Please upload the wil file you're trying to convert

**Comment by feitenging** [comment]
now find 2 errors.










------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Suprcode/mir2"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月28日(星期五) 上午6:32
收件人:&nbsp;"Suprcode/mir2"<mir2@noreply.github.com&gt;;
抄送:&nbsp;"情到深处"<563276225@qq.com&gt;;"State change"<state_change@noreply.github.com&gt;;
主题:&nbsp;Re: [Suprcode/mir2] LibEditor covert big Wil file error (#371)





 
Please upload the wil file you're trying to convert
 
—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub, or unsubscribe.


从QQ邮箱发来的超大附件

Wil.rar (105.54M, 2020年09月27日 14:46 到期)进入下载页面：http://mail.qq.com/cgi-bin/ftnExs_download?t=exs_ftn_download&k=5e3137652f6f569ca3d8a5441e31034a540051540f0004044f520451591c055c5a091a070f0906485a0204520a50535754060555383631320b5d191759433158&code=b17e811e

**Comment by Suprcode** [comment]
This file format is not supported. Unsure what WIL type it is, but the editors we use do not read this file correctly.

![image](https://user-images.githubusercontent.com/9963882/91557925-40e87e00-e92d-11ea-9ffa-843ab98df313.png)

**Comment by feitenging** [comment]
this Wil format is sure. i use mir3 LibEditor covert noproblem.  use normal Wil Editor(Viewer) open it also noproblem.

**Comment by Suprcode** [comment]
Thanks. That should be fixed now.

**Comment by feitenging** [comment]
LibEditor covert Mir3 GSP Wil file there&nbsp;is a&nbsp;endless&nbsp;loop
Attachment has a common Wil Viewer, It can be viewed normally Wil file.


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Suprcode/mir2"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月29日(星期六) 凌晨2:44
收件人:&nbsp;"Suprcode/mir2"<mir2@noreply.github.com&gt;;
抄送:&nbsp;"纯白的黑"<563276225@qq.com&gt;;"State change"<state_change@noreply.github.com&gt;;
主题:&nbsp;Re: [Suprcode/mir2] LibEditor covert big Wil file error (#371)





 
Thanks. That should be fixed now.

**Comment by Suprcode** [comment]
Please upload the example WIL file which is having the error.

**Comment by feitenging** [comment]
upload this.


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Suprcode/mir2"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年9月23日(星期三) 凌晨3:10
收件人:&nbsp;"Suprcode/mir2"<mir2@noreply.github.com&gt;;
抄送:&nbsp;"纯白的黑"<563276225@qq.com&gt;;"State change"<state_change@noreply.github.com&gt;;
主题:&nbsp;Re: [Suprcode/mir2] LibEditor covert big Wil file error (#371)





 
Please upload the example WIL file which is having the error.

**Comment by feitenging** [comment]
uploaded.
Excuse me, have you confirmed and fixed the problem?




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Suprcode"<notifications@github.com&gt;; 
发送时间: 2020年9月23日(星期三) 凌晨3:10
收件人: "Suprcode/mir2"<mir2@noreply.github.com&gt;; 
抄送: "纯白的黑"<563276225@qq.com&gt;; "State change"<state_change@noreply.github.com&gt;; 
主题: Re: [Suprcode/mir2] LibEditor covert big Wil file error (#371)





 
Please upload the example WIL file which is having the error.

**Comment by Suprcode** [comment]
Where have you uploaded it to? Unable to see any link.

**Comment by feitenging** [comment]
LibEditor covert Mir3 GSP Wil file there&nbsp;is a&nbsp;endless&nbsp;loop
Attachment has a common Wil Viewer, It can be viewed normally Wil file.



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Suprcode/mir2"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年9月24日(星期四) 上午6:01
收件人:&nbsp;"Suprcode/mir2"<mir2@noreply.github.com&gt;;
抄送:&nbsp;"纯白的黑"<563276225@qq.com&gt;;"State change"<state_change@noreply.github.com&gt;;
主题:&nbsp;Re: [Suprcode/mir2] LibEditor covert big Wil file error (#371)





 
Where have you uploaded it to? Unable to see any link.
