### ISSUE TITLE
LibEditor covert Mir3 GSP Wil file error

### ISSUE THREAD

**Issue by feitenging** [Suprcode/mir2#375]
LibEditor covert Mir3 GSP Wil file there is a endless loop
Attachment has a common Wil Viewer, It can be viewed normally Wil file.
[Mir3_Wil.zip](https://github.com/Suprcode/mir2/files/5287016/Mir3_Wil.zip)

**Comment by Suprcode** [comment]
This WIL format uses a different type of compression which isn't already in the source. Unless you know what the decompression is i'm not able to get it to be fully readable.

![image](https://user-images.githubusercontent.com/9963882/94352121-fd328280-0058-11eb-968b-cee138cc44f7.png)

**Comment by feitenging** [comment]
Here's one VB.Net code, It can be read completely.
But I don't know how to read Mask Image, Please fix it.
[WilClass.zip](https://github.com/Suprcode/mir2/files/5288857/WilClass.zip)
