### ISSUE TITLE
P_PatchFileName not found

### ISSUE THREAD

**Issue by baiachen** [Suprcode/mir2#377]
http://mirfiles.co.uk/mir2/cmir/patch/PList.gz

Error 1020
Access denied

**Comment by baiachen** [comment]
Where to download latest files？ Client ：/Data/*  /Maps/*

**Comment by MatrixHan** [comment]
> http://mirfiles.co.uk/mir2/cmir/patch/PList.gz
> 
> Error 1020
> Access denied

I had the same problem. How did you solve it.

**Comment by Suprcode** [comment]
This host is blocked in China and some other regions.
