### ISSUE TITLE
website

### ISSUE THREAD

**Issue by scriptkitz** [Suprcode/mir2#383]
can't open the website?
http://www.lomcn.org/
http://mirfiles.co.uk/

**Comment by JevLOMCN** [comment]
Both sites are up

**Comment by dragon-yuan** [comment]
help, website down

**Comment by JevLOMCN** [comment]
Both sites are up and running. 

Checked on [www.isitdownrightnow.com](url)

Please make sure your anti virus/ firewall isn't preventing you from accessing the site. this includes using a VPN
