### ISSUE TITLE
SQL support

### ISSUE THREAD

**Issue by Spinks90** [Suprcode/mir2#392]
Just wondering, how come SQL support hasn't been added rather than using `BinaryWriter` and then it's thread-safe and allows better scalability?

Same with the error logging, it's not thread-safe, you may as well use an existing library than writing your own such as `Serilog` and if you want to write it to a textbox using a sink. The current problem is if you get 2 files trying to write log at the same time you would get an `IOException`.

**Comment by Suprcode** [comment]
Plenty of reasons why it's not been converted to SQL, but the main one being no one has been able to provide a clean implementation of it which performs better than binary writing. One of the main selling points of crystal is that its 1 click to setup. Having a SQL requirement would put off a lot of people - and with majority of the live servers running fine on the existing database code it's not an important requirement.

And the logging uses log4net, not sure where you can see its a custom implementation. log4net is fully thread safe.

**Comment by Spinks90** [comment]
Yeah, I can understand the user having to install extra dependency. Performing better in what context? As in performance? 

I mean there is SQL Compact/SQLite which wouldn't require additional installed dependencies but wouldn't offer the scalability I was thinking of. It would be quite hard to beat raw performance, but you could use async SQL queries would help CPU a little. Though my suggestion about MSSQL wasn't really about gaining extra performance but the scalability aspect of it.

- Able to manage the data easier with SQL queries
- Backups
- Integrations (Paypal IPN, third party authentication such as ASP.NET Identity etc)
- Thread-safe
- And so on
- Cleaner code as you would just use a mapper without having to worry about order of saving for your POCO classes.


My bad, I was using older version of the code which someone had sent me.

Yeah, you're right with `log4net` I was using older version of the code which I got sent. Main reason just wanted to see what reasoning behind SQL was. Should really reviewed more up-to-date version.

**Comment by Suprcode** [comment]
Crystal loads the full database in to memory on load. Moving to SQL would mean you'd need to change that to load on demand, and would have a hit on the servers performance. You're basically needing to rewrite the entire core mechanics of how data is handled. You're also going to run in to issues with indexes and having to wait for SQL to write your data before you can use it - as opposed to the existing system which simply saves the data at routine points.

Backups are performed every few minutes already
Paypal and external authentication can easily be integrated with the built in web services
Doesn't need to be thread safe as loading/saving is done on a single thread.

If Mir had a large user base and scalability was a key factor then it's likely this would be moved to SQL - but majority of servers have a 200 max user count, and so the only bonus you're getting is easier data mapping and not having to perform custom versioning on schema changes.

**Comment by Spinks90** [comment]
Yeah, I wouldn't change the saving mechanics, you would likely have interval time to save the data using async code with UDTT wrapped in a transaction.

Okay, no worries. I'll leave as is.
