### ISSUE TITLE
Reasoning

### ISSUE THREAD

**Issue by Pete107** [Suprcode/mir2#398]
https://github.com/Suprcode/mir2/blob/7c980c539bf928386318fb982ee3801c6bedea75/Server/MirObjects/Monsters/BlockingObject.cs#L79

Spotted this while improving the Data range based on clients res.

Why is it broadcasting in a loop? surely it should just be sending to the player?

If it's intended I won't bother making the change.

**Comment by Suprcode** [comment]
Yeah seems odd to be in a loop when broadcast just does exactly that. Perhaps at one point there were more conditions to showing it.
