### ISSUE TITLE
Linux install mir2

### ISSUE THREAD

**Issue by Pantyhose-X** [Suprcode/mir2#443]
[Arch Linux](https://archlinux.org/) is a Linux distribution install mir2 ?
Linux has less resource consumption

**Comment by Suprcode** [comment]
The server runs on .NET Core, so can be ran on linux without any of the WinForms components if desired.

**Comment by xawoger** [comment]
Is it still possible to run it on Linux?

**Comment by JevLOMCN** [comment]
> Is it still possible to run it on Linux?

No you'd need to switch the win forms out for something compatible. Or use some VM

**Comment by Suprcode** [comment]
It is possible, the server library is a separate project with no reliance on the win form project
