### ISSUE TITLE
Client: type text in chart box should not use items

### ISSUE THREAD

**Issue by orchidea7** [Suprcode/mir2#449]
When I type 1-6 in chart box, it will use items.

**Comment by Suprcode** [comment]
![image](https://user-images.githubusercontent.com/9963882/122123976-8fb4c500-ce26-11eb-99e9-520c7ff53dc6.png)

Tested and can confirm there is no issue pressing a number whilst textbox is active.

**Comment by orchidea7** [comment]
sorry, the case is when I type @ without active the textbox will use item

**Comment by Suprcode** [comment]
You need to change your keybinds so SHIFT cannot be pressed when pressing a belt function. This should be the default. If you delete your keybinds.ini it will remake it with the defaults.

![image](https://user-images.githubusercontent.com/9963882/122181120-f9fa5380-ce80-11eb-890c-b868d1e047ee.png)

**Comment by orchidea7** [comment]
Thank you very much !
