### ISSUE TITLE
How can I successfully run this project code?

### ISSUE THREAD

**Issue by KevinAtlans** [Suprcode/mir2#458]
How can I successfully run this project code?

What profile do I need to use?

Where is it?

I'm using vs2019 now, but I can't run the client

Can someone give me some advice?

Or where can I find the relevant documents?

**Comment by Smir** [comment]
Check the 

> How can I successfully run this project code?
> 
> What profile do I need to use?
> 
> Where is it?
> 
> I'm using vs2019 now, but I can't run the client
> 
> Can someone give me some advice?
> 
> Or where can I find the relevant documents?

The guides are on lomcn
