### ISSUE TITLE
Effect of monster sandstorm  does not work.

### ISSUE THREAD

**Issue by shen2009fei** [Suprcode/mir2#465]

**Comment by shen2009fei** [comment]
Anybody can fix it? or leave some code clue how to add or update one monster spell and effect?

**Comment by Suprcode** [comment]
Please explain the issue in more detail. There is no monster called sandstorm.

Ensure you have the correct ai and effect numbers set in your database for all coded monsters, as listed in the code.

Not all monsters are coded yet.

**Comment by shen2009fei** [comment]
Hi Supercode,

I checked server some information as below:
![SandStorm](https://user-images.githubusercontent.com/11209360/142740431-6f7e2ccf-c0cd-4c25-a967-90bdb743135a.png)

client.exe and server.exe downloaded from released file, db and other cliend files download from jev's data
from this link:https://github.com/Suprcode/mir2-database/tree/main/Jev.


Thanks.

**Comment by shen2009fei** [comment]
i am curious that there is no sandstorm name exist in monser enumeration. That monster should be respawned in WhiteDragonHillSide map.

**Comment by Suprcode** [comment]
The full monster list by their name can be found on the wiki. Maybe you have a different name for it

http://wiki.mironline.co.uk/Monster_Database

You should note that naming the monster "Sandstorm" does not mean anything. You must give it the correct Image, AI and Effect for it to work correctly.
