### ISSUE TITLE
Release version, Can package the client together?

### ISSUE THREAD

**Issue by LLLLLLong** [Suprcode/mir2#466]
When I update the version, sometimes update the client to overwrite the original official version. But I want to revert to the official version of the client，If the release version is also packaged with the client, it would be great, thank you very much！

**Comment by Suprcode** [comment]
Sorry I don't understand. The Release version is the EXE only. Client files can be downloaded using the autopatcher which is provided with the correct link.

You can also turn it off in Mir2Config.ini file if you don't want it to download.

Please post on the forum for further help

https://www.lomcn.org/forum/forums/crystalm2-help.663/
