### ISSUE TITLE
Webview2 Runtime installation NOT found

### ISSUE THREAD

**Issue by dewxin** [Suprcode/mir2#470]
When I click the client app, I will get an error message.

Microsoft.Web.WebView2.Core.WebView2RuntimeNotFoundException: Couldn't find a compatible Webview2 Runtime installation to host WebViews. ---> System.IO.FileNotFoundException:

And after about 2 hours hacking ,I still cannot solve the problem..
Could someone please tell me how to handle it :)

**Comment by Suprcode** [comment]
https://developer.microsoft.com/en-us/microsoft-edge/webview2/

**Comment by dewxin** [comment]
> 

Thanks for your help in the first place, I have downloaded the Runtime before, still it didn't work..
And another problem (which seems more fatal) is I cannot download the client resource from the launcher website.

**Comment by Suprcode** [comment]
If you can't connect to the autopatcher then its because its blocked in your country unfortunately. 

The only requirement for WebView2 is that your have the Edge Browser installed, WebView 2 runtimes, and the remaining files which are supplied in the release files.

**Comment by dewxin** [comment]
> 



> If you can't connect to the autopatcher then its because its blocked in your country unfortunately.
> 
> The only requirement for WebView2 is that your have the Edge Browser installed, WebView 2 runtimes, and the remaining files which are supplied in the release files.

Though it didn't solve my problem, it solved my puzzle. It is nice talking to you. I will keep trying to solve the problem. Thank you 👍
