### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by angelk727** [Suprcode/mir2#472]
mir2-master\Server\MirObjects\Monsters\HoodedSummonerScrolls.cs

158        public override void Die()
159       {
160          switch (Info.Effect)
161           {
162               case 1:
163                   ActionList.Add(new DelayedAction(DelayedType.Die, Envir.Time + 500));
164                   break;
165               case 0:
166               case 2:
167               case 3:
168                //default:  
169                //base.Die(); ///err
170                   break;
171            }
172            base.Die(); /// correct

**Comment by Pete107** [comment]
How is this a bug?

When an AI has Effect 1 the death delay will be 500 msec later than any other monster.

Moving the base.Die(); outside of the switch statement will cause any AI with Effect 1 to just die rather than the specified delayed death.
