### ISSUE TITLE
proposal

### ISSUE THREAD

**Issue by angelk727** [Suprcode/mir2#473]
Wemade Mir2==== korea Mir2

1=======2        PlayAttackSound
2=======4        PlayFlinchSound
3=======5        PlayDieSound
4=======3        PlaySwingSound
5=======1        PlayDeadSound
6=======6        PlaySecondAttackSound
7=======7        PlayThirdAttackSound
8=======8        PlayFourthAttackSound
9=======9        PlayFithAttackSound

Save a lot of trouble

**Comment by Suprcode** [comment]
The sound for every monster which has complete Ai has already been done and added. At this point it would be more effort changing the whole sound system to another format.
