### ISSUE TITLE
 Hello, I need your help

### ISSUE THREAD

**Issue by ludayegmail** [Suprcode/mir2#474]
Hello, I use your server to add a portable trading and portable warehouse function, but the addition is unsuccessful. Can you help me see if it is a code error? If you can send me a manual, this is the following code

[@Main]
{
#IF
CHECKITEM 万能卷轴 1
#ACT
GOTO @Main-1
#ELSEACT
GIVEITEM 测试卷轴 1
GOTO @Main-1

[@Main-1]
#SAY
欢迎来到PC公益服务器.
感谢您参与测试.

<出售物品/@Sell>

<回购物品/@BuyBack>

<特殊修理/@SRepair>

[@Sell]
#SAY
你想出售什么物品?

[@BuyBack]
#SAY
世上没有后悔药,不过我这有

[@SRepair]
#SAY
你很幸运,我这刚好有做特殊修理用的材料.

[TYPES]
1
2
4
5
6
7
8
9
10
11
12
13
16
18
20

}

**Comment by Suprcode** [comment]
Hi. Please divert these questions to the forum

https://www.lomcn.org/forum/
