### ISSUE TITLE
Npc command CHECKCLASS

### ISSUE THREAD

**Issue by KingdomMir2** [Suprcode/mir2#475]
Can CHECKCLASS made to also check the amount of a class?  Like for the euro BattleGround npc you CHECKCLASS Warrior = 3

**Comment by Suprcode** [comment]
Hi. The CHECKCLASS only checks the current player. It would need to be a new command which checks against a whole map.

Feel free to put in the request on this forum thread.

https://www.lomcn.org/forum/threads/whats-next-for-crystal.104809/
