### ISSUE TITLE
++Mage skills

### ISSUE THREAD

**Issue by angelk727** [Suprcode/mir2#477]
Mage skills：HeavenlySecrets  function：MeteorStrike、Blizzard  No boot required

1/------mir2-master\Shared\Enums.cs"

   (public enum Spell 1176  line Approximate location +++):  ----------------------------------》》》》   

                    HeavenlySecrets = 56,

2/------mir2-master\Shared\Enums.cs"

    (public enum BuffType 1349 line Approximate location +++):  ----------------------------------》》》》    

                    HeavenlySecrets,

3/------------mir2-master\Server\MirObjects\PlayerObject.cs
  

            6598 line Approximate location +++):  ----------------------------------》》》》
                    case Spell.HeavenlySecrets:
                    HeavenlySecrets(magic, out cast);
                    break;
   
            8151 line Approximate location +++):  ----------------------------------》》》》

               private void HeavenlySecrets(UserMagic magic, out bool cast)
        {
            cast = true;

            ActionList.Add(new DelayedAction(DelayedType.Magic, Envir.Time + 500, magic));         

        }
           

             9124 line Approximate location +++):  ----------------------------------》》》》 
  
     #region HeavenlySecrets

                case Spell.HeavenlySecrets:
                    {
                        AddBuff(BuffType.HeavenlySecrets, this, (Settings.Second * 10) + (magic.Level * 10000), new Stats { [Stat.HeavenlySecrets] = (magic.Level + 1) * 2  });
                        LevelMagic(magic);
                    }
                    break;
                #endregion

4/------------mir2-master\Server\MirEnvir\Envir.cs

            324 line Approximate location +++):  ----------------------------------》》》》

            if (!MagicExists(Spell.HeavenlySecrets)) MagicInfoList.Add(new MagicInfo { Name = "HeavenlySecrets", Spell = Spell.HeavenlySecrets, Icon = 77, Level1 = 50, Level2 = 63, Level3 = 56, Need1 = 1000, Need2 = 2000, Need3 = 3500, BaseCost = 28, LevelCost = 2, MPowerBase = 1, PowerBase = 1, DelayBase = 600000, DelayReduction = 100000, Range = 0 , MultiplierBase = 1f, MultiplierBonus = 0f});
            

5/------------mir2-master\Server\MirDatabase\BuffInfo.cs

          46   line Approximate location +++):  ----------------------------------》》》》         

           new BuffInfo { Type = BuffType.HeavenlySecrets, Properties = BuffProperty.None, StackType = BuffStackType.ResetDuration, Visible = true },

6/------------mir2-master\Client\MirScenes\Dialogs\BuffDialog.cs

            423  line Approximate location +++):  ----------------------------------》》》》

                    case BuffType.HeavenlySecrets:
                    return 77;

7/------------mir2-master\Client\MirObjects\PlayerObject.cs

            1754   line Approximate location +++):  ----------------------------------》》》》

             #region HeavenlySecrets
                            case Spell.HeavenlySecrets:
                                Effects.Add(new Effect(Libraries.Magic3, 200, 8, Frame.Count * FrameInterval * 4, this));
                                Effects.Add(new Effect(Libraries.Magic3, 210, 7, Frame.Count * FrameInterval, this));
                                SoundManager.PlaySound(20000 + (ushort)Spell * 10);
                                break;
              #endregion

            2107   line Approximate location +++):  ----------------------------------》》》》Here is the modification!!!!!

               #region Blizzard

                            case Spell.Blizzard:
                                Effects.Add(new Effect(Libraries.Magic2, 1540, 8, Frame.Count * FrameInterval, this));
                                SoundManager.PlaySound(20000 + (ushort)Spell * 10);
                                int BlizzardTime = 0; 
                                if (!Buffs.Any(x => x == BuffType.HeavenlySecrets)) BlizzardTime = 0;
                                if (!Buffs.Any(x => x == BuffType.HeavenlySecrets)) BlizzardTime = 3000; 
                                BlizzardStopTime = CMain.Time + BlizzardTime;
                                break;

                            #endregion

                            #region MeteorStrike

                            case Spell.MeteorStrike:
                                Effects.Add(new Effect(Libraries.Magic2, 1590, 10, Frame.Count * FrameInterval, this));
                                SoundManager.PlaySound(20000 + (ushort)Spell * 10);
                                int MeteorStrikeTime = 0; 
                                if (!Buffs.Any(x => x == BuffType.HeavenlySecrets)) MeteorStrikeTime = 0;
                                if (!Buffs.Any(x => x == BuffType.HeavenlySecrets)) MeteorStrikeTime = 3000; 
                                BlizzardStopTime = CMain.Time + MeteorStrikeTime;
                                break;

                            #endregion

8/------------mir2-master\Client\MirObjects\MapObject.cs 
            
 
               139 line Approximate location +++):  ----------------------------------》》》》

                     case BuffType.HeavenlySecrets:
                    Effects.Add(new BuffEffect(Libraries.Magic3, 210, 7, 1400, this, true, type) { Repeat = true });
                    break;

9/------------mir2-master\Shared\Data\Stat.cs

                     156 line Approximate location +++):  ----------------------------------》》》》

                     HeavenlySecrets = 129,

**Comment by infinity1207** [comment]
@angelk727 I have another issue, i got the newest version code and compile is ok, but when Client.exe run, throw exception in SlimDX can you help me, thank you!
![image](https://user-images.githubusercontent.com/9922916/152628261-78eee077-6d87-422e-931c-7a5d9223b669.png)

**Comment by angelk727** [comment]
send emails

**Comment by KingdomMir2** [comment]
whats this do make you you unroot to move with met/blizz?

**Comment by angelk727** [comment]
Sorry, I don't understand what you said. Can you be more specific

**Comment by KingdomMir2** [comment]
what is this skill ment todo?

**Comment by angelk727** [comment]
function：MeteorStrike、Blizzard . No boot required   guide skills：MeteorStrike、Blizzard  Avoid Caton for 3 seconds

**Comment by KingdomMir2** [comment]
you mean not held in spot while the skill is going?

**Comment by KingdomMir2** [comment]
there is a korean skill fast move that does the same thing?

**Comment by angelk727** [comment]
Why don't you test it?

**Comment by Lilcooldoode** [comment]
If you have suggestions for the codebase. Please submit them in a PR for review rather than a difficult to read Issue like this.
