### ISSUE TITLE
skills：CounterAttack  (revised)

### ISSUE THREAD

**Issue by angelk727** [Suprcode/mir2#478]
skills：CounterAttack  (revised)

1/------mir2-master\Client\MirObjects\MapObject.cs

   (136  line Approximate location +++):  ----------------------------------》》》》   Here is the modification!!!!!

                    case BuffType.CounterAttack:
                    Effects.Add(new BuffEffect(Libraries.Magic3, 130, 8, 900, this, true, type) { Repeat = false });
                    SoundManager.PlaySound(20000 + (ushort)Spell.CounterAttack * 10 + 0);
                    Effects.Add(new BuffEffect(Libraries.Magic3, 140, 2, 800, this, true, type) { Repeat = true });
                    break;

2/------mir2-master\Client\MirObjects\PlayerObject.cs

    ( 2063 line Approximate location +++):  ----------------------------------》》》》    Here is the modification!!!!!

                     #region CounterAttack

                            case Spell.CounterAttack:
                                Effects.Add(new Effect(Libraries.Magic3, 160, 10, Frame.Count * FrameInterval, this));
                                SoundManager.PlaySound(20000 + (ushort)Spell * 10);
                                Effects.Add(new Effect(Libraries.Magic, 3480 + (int)Direction * 10, 10, 10 * FrameInterval, this));
                                Point location = Functions.PointMove(CurrentLocation, Direction, 1);
                                MapControl.Effects.Add(new Effect(Libraries.Magic3, 170, 6, 600, location, CMain.Time + 200));
                                SoundManager.PlaySound(20000 + (ushort)Spell * 10 + 5);

                                break;

                            #endregion

**Comment by angelk727** [comment]
The player can continue to use this skill after death. Failed to resolve the issue

**Comment by angelk727** [comment]
mir2-master\Client\MirScenes\GameScene.cs

10393  private void UseMagic(ClientMagic magic)
           {
            if (User.Dead) return; //+++++++++Show skills after solving the character's death. Get stuck
            if (CMain.Time < GameScene.SpellTime || User.Poison.HasFlag(PoisonType.Stun))
            {
                User.ClearMagic();
                return;

**Comment by angelk727** [comment]
mir2-master\Client\MirScenes\GameScene.cs

761 public void UseSpell(int key)
        {
            if (User.Dead) return; //+++++++++After the character dies, all skills can no longer be used
            if (User.RidingMount || User.Fishing) return;

**Comment by Lilcooldoode** [comment]
If you have suggestions for the codebase. Please submit them in a PR for review rather than a difficult to read Issue like this.
