### ISSUE TITLE
External IP cannot be set. How to add public IP

### ISSUE THREAD

**Issue by zhaokai1982** [Suprcode/mir2#487]
There is no public IP setting field in the generated server configuration file. This part is included in the code. Why not in the generated configuration file?

        //Network
        public static bool UseConfig = false;
        public static string IPAddress = "127.0.0.1";
        public static int Port = 7000;
        public const int TimeOut = 5000;

**Comment by KingdomMir2** [comment]
Best to post on lomcn in the c files bug forum too.

**Comment by zhaokai1982** [comment]
吉林爱尚智能影音已经查收此邮件，我们保证对所发资料的保密性。有合作意向随时联络。感谢您的配合。

**Comment by Suprcode** [comment]
The server doesn't care what your external IP is. Just enter your internal IP.

**Comment by zhaokai1982** [comment]
> 服务器不关心您的外部IP是什么。只需输入您的内部 IP。

Hello! Thank you for your reply. I may not explain the problem. The configuration file generated by the client does not have the setting of IP address. Quietly, which country are you from.

**Comment by zhaokai1982** [comment]
my perfect M2 version. All of this uses 32-bit color. Water flowers and grass are dynamic. Unfortunately, only the occupation is not perfect. It is still three occupations. We can exchange technology together.























> 最好在c文件错误论坛的lomcn上发布。


my perfect M2 version. All of this uses 32-bit color. Water flowers and grass are dynamic. Unfortunately, only the occupation is not perfect. It is still three occupations. We can exchange technology together.

**Comment by zhaokai1982** [comment]
Do you have an email to provide? Facilitate communication together
