### ISSUE TITLE
Importing database with new additional items causes exception error

### ISSUE THREAD

**Issue by Knotty1985** [Suprcode/mir2#508]
When re-importing an item database with a new item added to the list, it isn't given an index number and on trying to exit the form (to save it) an unhandled exception occurs

************** Exception Text **************
System.InvalidCastException: Specified cast is not valid.
   at Server.Database.ItemInfoFormNew.SaveForm() in F:\VS Projects\mir2\Server.MirForms\Database\ItemInfoFormNew.cs:line 291
   at Server.Database.ItemInfoFormNew.ItemInfoFormNew_FormClosed(Object sender, FormClosedEventArgs e) in F:\VS Projects\mir2\Server.MirForms\Database\ItemInfoFormNew.cs:line 884
   at System.Windows.Forms.Form.OnFormClosed(FormClosedEventArgs e)
   at System.Windows.Forms.Form.CheckCloseDialog(Boolean closingOnly)

(Tested with a replica of an existing item with only a name change)

**Comment by damianday** [comment]
I can't reproduce thi is this with the lastest source?

**Comment by Knotty1985** [comment]
Resolved, missed current build's additional columns (importing DB file without the additional columns caused the error), exported new copy and copied items over and reimported without issue.

**Comment by Knotty1985** [comment]
Reopening this as there probably needs to be a solution to allow an older DB to be imported without being an issue when it does not contain columns that exist following an update. (e.g the new columns added yesterday were not in my export)

Copying data between exports works but avoiding wrongly pasted data into the new cells is a task that could be avoided if missing columns can be ignored and set to null/0

**Comment by Suprcode** [comment]
This only happened because existing fields were missing from the new item dB.

Feel free to raise the issue on lomcn in the bug section, however it's a very low priority feature as the item info hardly ever gets changes
