### ISSUE TITLE
New graphical glitch

### ISSUE THREAD

**Issue by Knotty1985** [Suprcode/mir2#512]
Came across a random graphical glitch that causes a ghosting effect that doesn't disappear until you log out.

To make this occur without fail during testing, in Bichon Provice, teleport to a dark location on same map (e.g. 260 580) with no candle etc equipped, then teleport back to 330 260

I have a video showing this but it's too big to upload so a screenshot is the best I can do

![image](https://user-images.githubusercontent.com/64409265/162541299-b071477c-94c5-47cd-9140-ddb5f7485c14.png)

**Comment by Knotty1985** [comment]
**Exception thrown: 'SlimDX.Direct3D9.Direct3D9Exception' in SlimDX.dll**

This error appears at the time of occurrence in debug

**Comment by zhaokai1982** [comment]
I have encountered similar problems. There are small red spots on the screen, and the NPC logo left by a large map disappears after logging off. The problem is that the dynamic link library of DX is disconnected.

**Comment by zhaokai1982** [comment]
The solution is perfect. It's hard, everyone
