### ISSUE TITLE
New account - Password "states" invalid when correct

### ISSUE THREAD

**Issue by Knotty1985** [Suprcode/mir2#516]
When creating a new account, if the password is valid and accepted, a pop up appears to say the password was not acceptable but the account is created and works.

**Comment by Lilcooldoode** [comment]
Not sure what you mean? - I just created 2 accounts with no issues

**Comment by Knotty1985** [comment]
It only seems to occur if you build the client.exe and test it, if you debug (using debug or release) in VS, the issue doesn't occur

I was mistaken however, it is not the password it is "the account ID is invalid" directly followed by "account created successfully"

**Comment by Lilcooldoode** [comment]
I still cant make this happen. You able to get a video or something?

**Comment by Knotty1985** [comment]
Closing this, unknown cause but seems to be resolved now
