### ISSUE TITLE
For the problem of attack target locking, it is suggested that experts repair and improve it。

### ISSUE THREAD

**Issue by zhaokai1982** [Suprcode/mir2#520]
There are some problems in attack target locking. When the locked target dies and no new target is selected, the locked target continues to execute until the new target is locked, or the locked target has left, but still continues to lock. Ideally, the locked target is beyond the attack range, the locked target is disconnected, the locked target is not disconnected in the current screen, and the locked target is disconnected when it dies.

**Comment by Lilcooldoode** [comment]
Have just tested this and seems to be working fine? Target is lost when it dies or leaves screen

**Comment by zhaokai1982** [comment]
Guys, you're all online!

**Comment by zhaokai1982** [comment]
You use archers to test, and mages. If the monster dies and you don't choose other monsters, he will automatically turn to the direction of the dead monster and launch the skill. Not controlled by mouse position.

**Comment by zhaokai1982** [comment]
I was in the forum yesterday, and how to turn the head up under attack into equipment attribute suppression, which is similar to no run-up. With this special attribute, you can prevent being attacked and look up, such as adding it to your helmet. This avoids the use of plug-ins to assist.

**Comment by Lilcooldoode** [comment]
> You use archers to test, and mages. If the monster dies and you don't choose other monsters, he will automatically turn to the direction of the dead monster and launch the skill. Not controlled by mouse position.

I still cant make this happen. I tested it with Thunderbolt, what skill are you using with mage?

**Comment by zhaokai1982** [comment]
When you use magic or bow and arrow to kill monsters, don't use the mouse to get new monsters. At this time, you press the skill shortcut key to use spells. He will prompt in the upper left corner that you are too far from the target. Or some skills that do not belong to the attack class will not be used. They are killed before locking, or they hit an undead monster. The premise is that you should be far away from this monster. I have another problem, that is, after updating the pull, the transparency of the chat window becomes black and no longer transparent. I didn't find the problem. I read the code a lot.
