### ISSUE TITLE
Map guost problems

### ISSUE THREAD

**Issue by KingdomMir2** [Suprcode/mir2#521]
happens after teleporting out and then back to the centre of BW
or any other area where there are NPCs
mobs sometimes also ghost.. but if you run around they eventually all disappea
![Untitled](https://user-images.githubusercontent.com/54754739/163467101-8acd1dc4-b753-47ce-8680-eac093381e9d.png)

**Comment by zhaokai1982** [comment]
I also have this problem, but it has been solved. Update here.
I rewritten the following code to solve the problem. The problem only appears in the safe area. The problem of updating the back to town scene is not cleaned up after redrawing.
https://github.com/Suprcode/mir2/commit/cb175f44102e36dca4cffdfe01d1c81790facc8e
https://github.com/Suprcode/mir2/commit/4077a1ab36f53c68aa94d377b00e5182e54666b7
