### ISSUE TITLE
The gold coin is in the language file, and the translation of other languages is invalid. I have repaired it. I hope the code will also repair this item

### ISSUE THREAD

**Issue by zhaokai1982** [Suprcode/mir2#526]
The gold coin is in the language file, and the translation of other languages is invalid. I have repaired it. I hope the code will also repair this item

**Comment by angelk727** [comment]
Hello! How did you solve the crash problem related to the update of "observe" after April 27?

**Comment by zhaokai1982** [comment]
If you find a problem, you need to change the latest database, otherwise you will get an error

**Comment by angelk727** [comment]
It seems that it can't fundamentally solve the problem. If you use random and return to city scrolls in the game, it can quickly lead to collapse.

**Comment by angelk727** [comment]
Of course, if you use an unmodified older version, such as mir2 database main \ JEV, there will be no crash. That's why they won't crash when writing this code. The problem may be the compatibility of "server. Mirdb"
