### ISSUE TITLE
LibraryEditor:Can't parse the Shanda game resource file wil correctly?

### ISSUE THREAD

**Issue by dwbeta** [Suprcode/mir2#527]
I encountered some problems when reading the Shanda game resource file wil, for example, when exporting the resource format to lib, the array will be out of bounds, and after repairing the data out of bounds, the color of the exported image will be incorrect.
I guess there is something wrong with reading the wil palette? But in the same situation, I can read and display it correctly with MonGame, and the reason is unexplainable.

**Comment by dwbeta** [comment]
![image](https://user-images.githubusercontent.com/11530204/166106180-86c75ce5-6261-452a-9acd-c0cd8282cd50.png)

**Comment by Suprcode** [comment]
That client doesn't look like crystal. Issues raised here should be specifically related to the untouched crystal source.

if the crystal library editor cannot open an official WIL, please upload an example of the library so it can be inspected.

**Comment by dwbeta** [comment]
Only part of the resource files on the client side have been modified by me to read Shanda game resource files. At present, the problem has been solved. Thanks for providing such an excellent open source project.
