### ISSUE TITLE
Map file rendering is misplaced or wrong

### ISSUE THREAD

**Issue by dwbeta** [Suprcode/mir2#531]
Using the WeMade resource format wil, the rendering of the map file (Object) is misplaced, and the wil converts the lib resource format but it is normal. After comparing the two files, there is no difference between the two files. I don't know where there is a problem.

![image](https://user-images.githubusercontent.com/11530204/168503864-1e941a46-2dd8-4316-9b28-2905fc1e78c7.png)

**Comment by zhaokai1982** [comment]
你这个是地图文件 MAP的问题，绘制采用的读取文件不对，不能用最新的盛大map文件或者韩国最新的map文件
