### ISSUE TITLE
Character and guild names are reversed

### ISSUE THREAD

**Issue by OuYangPlane** [Suprcode/mir2#541]
The position of the character's name in the official MIR2 server is above the guild's name. The positions of the two in the crystal are reversed, and the guild's name and the character's name have the same size and the same font.

**Comment by OuYangPlane** [comment]
OK

**Comment by Suprcode** [comment]
This isn't a place to log issues until you've fixed it in your own source. If it's still an issue please leave the ticket open, or provide the fix publicly.
