### ISSUE TITLE
GIVEBUFF NPC Command doesn't give buffs correctly

### ISSUE THREAD

**Issue by ValhallaMir** [Suprcode/mir2#594]
As title.

Trying to give exp buff using GIVEBUFF NPC command in Login.txt and it just doesn't do anything, not a single thing.

**Comment by Suprcode** [comment]
the AddBuff command only works now for commands with no added stats. Likely the login.txt is just outdated and needs fixing, but this bug section is for code issues only, not database/script issues.

Will leave open for until I can verify that it's script related only.

**Comment by Suprcode** [comment]
as per my comment last year, the GIVEBUFF npc command is pretty much a useless command now. it wouldn't do anything but look pretty in the top right of your screen.

buffs have always been designed for a specific usecase, such as spells or items. the command might as well just be removed from the wiki altogether.

**Comment by JevLOMCN** [comment]
> as per my comment last year, the GIVEBUFF npc command is pretty much a useless command now. it wouldn't do anything but look pretty in the top right of your screen.
> 
> 
> 
> buffs have always been designed for a specific usecase, such as spells or items. the command might as well just be removed from the wiki altogether.

I don't see why it can't be re-coded back in to work, it's a good feature.

**Comment by JevLOMCN** [comment]
I'd suggest closing the bug, I will remove the GIVEBUFF from the wiki and will release a Suggestion thread under Crystal Mir 2 Development section.
