### ISSUE TITLE
ThunderElement AI - Kills Server Cycles

### ISSUE THREAD

**Issue by EliteMir** [Suprcode/mir2#611]
https://github.com/Suprcode/mir2/blob/master/Server/MirObjects/Monsters/ThunderElement.cs

Something in this AI causes the server cycle delays to go into the thousands and grind the server to a halt.

It doesn't produce a crash log, as it just hammers the cycle delays to the point of people not being able to move.

I noticed in the CompleteAttack, there's no protection like other AIs for example.. 
"if (target == null  !target.IsAttackTarget(this)  target.CurrentMap != CurrentMap || target.Node == null) return;"

@Suprcode - Any chance you can review the AI? I suspect its related to pets and targeting pets that have teleported, but I'm struggling to replicate it offline (happens straight away on live when loads of people are on).

**Comment by Suprcode** [comment]
As discussed on discord I don't believe this AI to be the issue - most likely something else calling this AI. Will need an error log to be sure its this AI specifically.
