### ISSUE TITLE
All conquest NPCs disappear during wars with no option to toggle

### ISSUE THREAD

**Issue by EliteMir** [Suprcode/mir2#653]
If you use the tax system for wars, all your NPCs will vanish during wars.

There is currently no way to stop this, which limits the taxing options available without making half/all the province NPCs vanish.

**Comment by grimchamp** [comment]
Not sure what tax system is. Can you explain?

**Comment by JevLOMCN** [comment]
NPC checkbox will be added adjacent to Only visible at set times on the NPC's Visibility tab.
Will be set to enabled as default.
Text will read: Visible during Conquest.
