### ISSUE TITLE
New forms data loss when filters applied

### ISSUE THREAD

**Issue by EliteMir** [Suprcode/mir2#660]
If you have filters applied when closing/saving the form, it causes data loss and will occasionally revert changes made due to the filter being applied.

Workaround currently is ensure filters are cleared before closing or enjoy doing it all again.

**Comment by JevLOMCN** [comment]
Tested this and it seems very inconsistent.
Sometimes when using the search box and then editing an item's stats and closing it will stick and sometimes it will revert.
I can't pinpoint exactly what step needs to take place for the form to reset.
Sometimes clicking an empty box with no item data will cause it to reset but sometimes it dosen't.
