### ISSUE TITLE
Starting the game is currently disabled.

### ISSUE THREAD

**Issue by FuckingKing** [Suprcode/mir2#672]
When a character is selected to start, a prompt will pop up “Starting the game is currently disabled.”
how can i start？

**Comment by FuckingKing** [comment]
![image](https://user-images.githubusercontent.com/7135632/222110320-62ae4c19-280f-4c52-bcd8-526ccc925abd.png)

**Comment by JevLOMCN** [comment]
Server>Configs>Setup.ini 

StartGame=True

**Comment by Sanjian** [comment]
or click the tickbox on the server options permission... fuckingking... more like fuckingdonkey...

![image](https://user-images.githubusercontent.com/12431882/222506322-3aadd6f1-2e2e-4136-a6dd-fc63e1f2ae30.png)

**Comment by FuckingKing** [comment]
> or click the tickbox on the server options permission... fuckingking... more like fuckingdonkey...
> 
> ![image](https://user-images.githubusercontent.com/12431882/222506322-3aadd6f1-2e2e-4136-a6dd-fc63e1f2ae30.png)

thanks buddy,  it's a family name
