### ISSUE TITLE
Archiving deleted players will cause a complete database corruption

### ISSUE THREAD

**Issue by EliteMir** [Suprcode/mir2#685]
I don't have the crash log anymore, as I've since disabled this function.

But upon archiving deleted players (that exist in guilds), it will kill your database with tons of null references.

**Comment by grimchamp** [comment]
I believe this to be an issue with loading from different database versions.  I cannot recreate in current db version (107).
Tried the following:

- make a character
- make a guild
- archive character
- restore character
- delete character
- archive character
- restore character

rebooted between each archive / restore to no avail.
