### ISSUE TITLE
Transforms shouldn't provide FastRun aka MirBoots

### ISSUE THREAD

**Issue by EliteMir** [Suprcode/mir2#692]
Can't see why this would be correct by default?

 case BuffType.Transform:
                            TransformType = (short)buff.Values[0];
                            FastRun = true;
                            break;

FastRun should definitely not be given on all transforms.

**Comment by Suprcode** [comment]
That's how it works on official files

**Comment by JevLOMCN** [comment]
Can this be closed. It can be changed in the code so the option can be adjusted by the server owner
