### ISSUE TITLE
No Light Parameter added to SpellObjects

### ISSUE THREAD

**Issue by EliteMir** [Suprcode/mir2#693]
Currently spells like Met, PC, Blizz, Firewall etc have no light.. they should.

**Comment by JevLOMCN** [comment]
![image](https://user-images.githubusercontent.com/68875342/227856986-c5803882-3f4a-43f9-aa5e-7713e8d4d530.png)
![image](https://user-images.githubusercontent.com/68875342/227856995-5461af9b-1e94-47a2-b3ce-600b335ef842.png)

Firewall looks fine?
