### ISSUE TITLE
Holding SHIFT + 1 Macro conflicts with !

### ISSUE THREAD

**Issue by EliteMir** [Suprcode/mir2#697]
It conflicts with the ! command as SHIFT + 1 is both SHOUT and POT

  switch (e.KeyChar)
            {
                case '@':
                case '!':
                case ' ':
                case (char)Keys.Enter:
                    ChatTextBox.SetFocus();
                    if (e.KeyChar == '!') ChatTextBox.Text = "!";
                    if (e.KeyChar == '@') ChatTextBox.Text = "@";
                    if (ChatPrefix != "") ChatTextBox.Text = ChatPrefi

**Comment by Suprcode** [comment]
The keybind system already accommodates this. You just need to tick the "strict" checkbox when remapping it. This will stop 1 from being triggered if you're pressing any key as well as 1.

Some people prefer it the other way around - so it should not be hard coded.
