### ISSUE TITLE
Town Teleport

### ISSUE THREAD

**Issue by JevLOMCN** [Suprcode/mir2#709]
Encountered a bug where the TownTeleport won't work. 

This can only be resolved by the player returning to a safezone, relogging does not work.

Is the server failing to detect the last SZ the player visited?

**Comment by grimchamp** [comment]
Could not recreate. Can you list steps to get into this condition?

**Comment by JevLOMCN** [comment]
> 

I can’t replicate this either but I did witness this, I’ll close the report for now.
