### ISSUE TITLE
.Net7  Publish single file for client

### ISSUE THREAD

**Issue by fluttergo** [Suprcode/mir2#722]
The process was terminated due to an unhandled exception.

Exception Info: System.BadImageFormatException: Could not load file or assembly 'D:\CrystalMir2\Build\Client\SlimDX.dll'. 

".Client.csproj":
````
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net7.0-windows</TargetFramework>
    <Nullable>disable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>disable</ImplicitUsings>
    <ApplicationIcon>MIR2.ICO</ApplicationIcon>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <PlatformTarget>x64</PlatformTarget>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <BaseOutputPath>..\Build\Client\</BaseOutputPath>
    <IncludeNativeLibrariesForSelfExtract>false</IncludeNativeLibrariesForSelfExtract>
    <SelfContained>true</SelfContained>
    <PublishSingleFile>true</PublishSingleFile>
  </PropertyGroup>
````

SlimDx.dll PE
```
// D:\CrystalMir2\Build\Client\SlimDX.dll
// SlimDX.dll
// EnterPoint 0x0011EFF0
// Architecture:x64
//RunningTime: .NET Framework 4
```

**Comment by JevLOMCN** [comment]
Make sure you have all dependencies downloaded from here -(https://www.lomcn.org/forum/threads/fao-people-with-black-screen-issues.88388/#post-976715)

**Comment by fluttergo** [comment]
‘PublishSingleFile’ is a new feature base on .net7 

All is work ， if I do not use  this feature

**Comment by thedeemer** [comment]
You can't pack SlimDX.

**Comment by grimchamp** [comment]
This should fix the problem:

<IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract> 

However it may be best to keep some files excluded from this so you will need to review it.

There are pros and cons to self publishing.  In this case yes, the end user will not need to pre-download .NET7 as it is published in the client which is a bonus however upon execution the .exe still needs to extract all files to %TEMP% which takes resource, time and cpu.  

I would be careful with this choice and do some good research into whether it is right for this application.


This ticket needs closed however - it is not an issue of crystal code, it is an issue of self publishing in .net.
