### ISSUE TITLE
The archer's skill "StoneTrap" has a problem. 

### ISSUE THREAD

**Issue by SeieiFSetsuna** [Suprcode/mir2#724]
The archer's skill "StoneTrap" has a problem. The stone pillar always exists and has no expiration date. Finally, I used the GM command "@ CLEARMOB" to temporarily solve this problem.
It's like a loyal follower, following the character wherever he goes. Even if the character comes back online, it still really exists behind you.

**Comment by JevLOMCN** [comment]
Please make sure you’ve given the Monster a HP Value and that you’ve given it the correct AI number.

**Comment by SeieiFSetsuna** [comment]
After the results of the investigation just now,
The value of the StoneTrap monster's current database attribute is:

Name：StoneTrap
AI：0
Effect：0
Level：50
Light：0
Attack Speed：2500
Move Speed：0
View Range：7
Cool Eye：0
Experience：0
Can Push：√
Auto Rev：√
Undead：
Can Tame：√
Drop Path：
Min AC：15
Max AC：20
Min MAC：15
Max MAC：20
Min DC：15
Max DC：20
Min MC：0
Max MC：0
Min SC：0
Max SC：0
Accuracy：0
Agility：0
HP：1000

Please help me analyze what the problem is, thank you!

**Comment by grimchamp** [comment]
Hi @SeieiFSetsuna, this will actually miss the next PR but be first action in the next and will get pushed in as part of its own PR.
