### ISSUE TITLE
Gameshop CreditxGold Calculation

### ISSUE THREAD

**Issue by JevLOMCN** [Suprcode/mir2#730]
The Credit x Gold Calculation system is broken and changing the credit value of an item doesn't change the gold value.

![image](https://user-images.githubusercontent.com/68875342/229289616-a02fbc1f-2913-452a-bd3c-1441a1136744.png)

**Comment by Suprcode** [comment]
works fine for me. set it to 100, then change credit price - the gold price will automatically change to creditx100

obviously you can manually change gold price to override this default
