### ISSUE TITLE
Patcher bug

### ISSUE THREAD

**Issue by JevLOMCN** [Suprcode/mir2#734]
The auto patcher will reset after every exit if the drive the client is on is ExFAT or FAT32.
The only drive that would work is a NTFS drive.
I know it's easy to format a drive to be NTFS but what's stopping the client from downloading on exfat/fat32?

**Comment by Suprcode** [comment]
Sounds like a permission thing more than any code issue. However last time anyone used fat32 formatting was in the 90s anyway right?

**Comment by JevLOMCN** [comment]
Yea however some new thumb drives and external HDDs still come with exfat/fat32 format. I've tested a little with permissions on the drive themselves and it dosen't seem to 'fix' the patcher resetting. Could the client be coded to only look for the directory inside an NTFS format? Would it be good to implement the ability for it to run off either?

**Comment by Suprcode** [comment]
There's no code for saving files on specific drive formats.

Seems like a very strange thing to do, and I suspect any game or application you attempt to directly install on to thumb drives will have similar issues.

This isn't an issue that needs solving
