### ISSUE TITLE
Focus

### ISSUE THREAD

**Issue by JevLOMCN** [Suprcode/mir2#737]
Archer's Focus spell doesn't give the player increased Accuracy.

Skill description: Passively increases chance to hit with physical attacks. Can also proc a critical attack to do extra damage.

**Comment by Suprcode** [comment]
Focus just doubles your range accuracy bonus.

Remember none of the archer skills follow official - so its useless comparing it to how it "should" work against official wemade mechanics.

**Comment by JevLOMCN** [comment]
I've compared it to the description you gave on the crystal wiki

**Comment by Suprcode** [comment]
Wiki needs updating then, I checked code and all its ever done is double your range chance

**Comment by Suprcode** [comment]
I've removed second part from the wiki - not sure why it was that originally, maybe the rough descriptions were originally taken from another location, or added by someone else - as using the word "proc" is not something i'd do myself
