### ISSUE TITLE
"No Fight" Map attribute wrongly affecting Map Spells

### ISSUE THREAD

**Issue by ValhallaMir** [Suprcode/mir2#739]
As title, the "No Fight" map attribute is stopping map spells from damaging monsters.

"No Fight" should stop PvP but allow PvE. All other spells work when a map is set to "No Fight" its only the map spells like FireWall, Blizzard, MeteorStrike, to name a few that are broken.

**Comment by grimchamp** [comment]
as you attack something, code will call IsAttackTarget().
IsAttackTarget for both map (of which monster inherits) and Player contain the following line in their implementation of IsAttackTarget():

if (CurrentMap.Info.NoFight) return false;
