### ISSUE TITLE
King Scorpion AI

### ISSUE THREAD

**Issue by JevLOMCN** [Suprcode/mir2#757]
The two-step attack (Lightning attack) is not currently working.

![image](https://user-images.githubusercontent.com/68875342/230598240-b06811eb-9734-4233-90f3-f78ca1b56ff1.png)

It currently deals damage if MC stats are given to the monster but the image being displayed is wrong.

**Comment by JevLOMCN** [comment]
Looked into Lib 75 and the lightning images are there. Is it a code issue or a lib issue with the lightning not being set under Frames?

**Comment by MousaEqilan** [comment]
change 272 to 544 and try from here 

 Effects.Add(new Effect(Libraries.Monsters[(ushort)Monster.KingScorpion], 272 + (int)Direction * 8, 8, Frame.Count * Frame.Interval, this)); 
 this should fix the attack effect

**Comment by MousaEqilan** [comment]
![image](https://user-images.githubusercontent.com/22372433/230742128-33dc2040-04ce-4eee-94b2-28413c6ce790.png)
