### ISSUE TITLE
QOL: Allow RecallMob and Mob to work off index id

### ISSUE THREAD

**Issue by grimchamp** [Suprcode/mir2#761]
Currently you need to type the full name for @RecallMob and @Mob to work. These should also allow the monster index id's.

**Comment by Suprcode** [comment]
I guess it's probably because mir servers may be new to you in general, but I've no idea why you'd ever prefer to spawn a monster by an ID rather than its name. Who's remembering the ID of all the monsters in their DB 🤣

**Comment by grimchamp** [comment]
I am when testing :D

**Comment by JevLOMCN** [comment]
Might be worth noting that if this is implemented it may cause server crashes if @mob is used with an index number that is not being used by a monster.

Either the monster was deleted and the index number is now just a gap
or
You have 200 mobs and you try and @mob 300 for example

**Comment by grimchamp** [comment]
It does same checks as entering name for determining if it exists.
