### ISSUE TITLE
STARTCONQUEST NPC ACT Command

### ISSUE THREAD

**Issue by JevLOMCN** [Suprcode/mir2#769]
STARTCONQUEST [ConquestID] 

Seems to be broken?

I have SabukWall as Conquest ID 1 in the database.

NPC script below is an example.

[@Main]
#SAY
Force Start <Sabuk War/@StartWar>

[@StartWar]
#ACT
STARTCONQUEST 1
LocalMessage "Sabuk Wall Started." Hint
#ELSEACT
LocalMessage "Sabuk War is currently on." Hint

**Comment by Suprcode** [comment]
Not sure about the command itself, but your elseact will never work, as that's not how NPC scripts work

**Comment by grimchamp** [comment]
RIP

**Comment by JevLOMCN** [comment]
I'll stick with #ElseSay

**Comment by Suprcode** [comment]
ElseSay still wouldn't trigger unless you have an IF
