### ISSUE TITLE
Taoist Hero Pets

### ISSUE THREAD

**Issue by JevLOMCN** [Suprcode/mir2#790]
Currently found the following two bugs:

1: Guard1 (AI 58) currently kills Taoist's pets BoneFamiliar/Shinsu/Deva, however, doesn't kill a Taoist Hero's pets. Is this because a hero's pet doesn't classify as a pet of a character but a hero instead which is already classified as a pet?

2: Taoist Hero Pets do not display a HP bar like the Hero itself.

**Comment by thedeemer** [comment]
Since when does Taoist hero's get pets?? 🤔 you sure that's correct?

**Comment by JevLOMCN** [comment]
They don't however a server owner might have it changed so they do with a small item attribute change. 
Having it defaulted to Kill the hero's pets would be better in the use case of a server releasing with this enabled.

**Comment by grimchamp** [comment]
Is this not out of scope as korea official doesn't support hero pets?
