### ISSUE TITLE
Huge spacing between quests?

### ISSUE THREAD

**Issue by RyanTaplin1705** [Suprcode/mir2#8]
What's with the huge spacing between quests? Is this intentional?

![untitled](https://cloud.githubusercontent.com/assets/11903234/7107968/705b4ad0-e16f-11e4-8164-a9fbbb3ba29d.png)

**Comment by Suprcode** [comment]
yeah it's been designed like that to separate them - any closer and it just become harder to read. Since you can only have a max of 5 quests on the screen anyway i didn't see this as an issue.
