### ISSUE TITLE
ShadowStep

### ISSUE THREAD

**Issue by mushaaban** [Suprcode/mir2#806]
Shadowstep not in sourcecode yet

**Comment by thedeemer** [comment]
This isn't an official skill, completely custom?

**Comment by Suprcode** [comment]
Isn't it a monk skill or something from shanda? Sounds familiar, maybe seen it in chrons?

**Comment by Suprcode** [comment]
Full list of official skills can be found here. I believe this is actually a mir3 assassin skill.

https://www.mir2db.com/list/52
