### ISSUE TITLE
Cannot pick items up once over weight

### ISSUE THREAD

**Issue by JevLOMCN** [Suprcode/mir2#814]
I seem to remember a time when you could go past the bag weight limit and it would force your character to walk, I don't know if it's still in without testing but I remember it happened on some occasions but now dosen't seem to appear.

**Comment by JevLOMCN** [comment]
You should be able to pick up items beyond the weight limit on the player's bag.

Only stopping once all bag slots are filled. 
When over weight the server limits you to walk only until you go below your bag weight again. It's like this in official.

**Comment by Suprcode** [comment]
That's nothing like the issue you wrote or the title of the bug. I've renamed the title to make sense to that issue lol.
