### ISSUE TITLE
How to use server.exe correctly in the windows server ?

### ISSUE THREAD

**Issue by jokester-joestar** [Suprcode/mir2#831]
I set the following settings in the Server Config Form
----------------------------------------------------------------
IP Address: 127.0.0.1
Port: 7000
TimeOut: 10000
Max User: 50
√ Start HTTP Service
HTTP IP Address: http://My Server IP: 5679
HTTP Trusted IP Address: My Server IP
----------------------------------------------------------------
I want to play Mir2 with my friends, so I rented a cloud server with a Windows system.
I made changes to the code in the client.
Client/Settings. cs line: 82-83
`Public static string IPAddress="My Server IP";`
`Public static int Port=5679;`

Do I need to change any other settings?
Or do cloud servers have some special settings?
Thank you very much

**Comment by jokester-joestar** [comment]
Sorry, I forgot to add an error in the console output.
SocketException (10022)

**Comment by jokester-joestar** [comment]
> This is not an issue and should be posted on lomcn.

I understand your suggestion. But the window is simple enough, and I think I have done my best. Server as part of the source code, Is there a problem with the functionality? Have you confirmed such issues?

**Comment by JevLOMCN** [comment]
You don’t need to adjust the server’s IP via the code, just change it in the Server’s Setup.Ini file located in the server’s config folder.

To allow friends to join please following the link below to my Port Forwarding guide.
https://www.lomcn.net/forum/threads/port-forwarding.106595/

A link you also might find useful is: https://www.lomcn.net/forum/threads/crystal-tutorial-wiki.109789/

**Comment by jokester-joestar** [comment]
> You don’t need to adjust the server’s IP via the code, just change it in the Server’s Setup.Ini file located in the server’s config folder.
> 
> To allow friends to join please following the link below to my Port Forwarding guide. https://www.lomcn.net/forum/threads/port-forwarding.106595/
> 
> A link you also might find useful is: https://www.lomcn.net/forum/threads/crystal-tutorial-wiki.109789/
Thank you for your generous help, I don't have any more questions.
