### ISSUE TITLE
Import NPC dont work

### ISSUE THREAD

**Issue by frangaliano** [Suprcode/mir2#845]
I have done the following process:

Export of NPCs to csv through server options.
Deletion of the NPCs in the server databases.
I have tried to import the same file that generates the export and no value is imported.

I would appreciate it if you will review this error and try to correct it.

Thanks and regards,

**Comment by whalefish30** [comment]
On top of this if you view npc script via the server it creates a new csv file rather than open the existing txt.

**Comment by JevLOMCN** [comment]
> On top of this if you view npc script via the server it creates a new csv file rather than open the existing txt.

You are using the latest code? (Not release)

**Comment by whalefish30** [comment]
Revision 3189 10th July last log.

**Comment by JevLOMCN** [comment]
Yea, Please use the latest code which includes a patch for the above issue. [LINK](https://github.com/Suprcode/mir2/archive/refs/heads/master.zip)

**Comment by JevLOMCN** [comment]
@Suprcode please close this as fixed.
