### ISSUE TITLE
Ghost Graphics

### ISSUE THREAD

**Issue by JevLOMCN** [Suprcode/mir2#846]
Net 7 has broken some graphical code causing mobs and players to 'ghost' 

Links to thread:
Bug - [Ghost mobs being targeted](https://www.lomcn.net/forum/threads/ghost-mobs-being-targeted.111136)

**Comment by gaodayihao** [comment]
This is not caused by upgrading to .net7 absolutely.
It is related to TargetObject, see the PR above.
