### ISSUE TITLE
intermittent characterinfo null

### ISSUE THREAD

**Issue by qkrtjdwns123** [Suprcode/mir2#850]
I'm not sure if this symptom fits this title.
Most crash the server.
But when it doesn't collide, it seems that something like this happens.
I am using the latest crystal server code.

Skill repeats infinitely.
Script item not used (item is deleted but has no effect)
NPCs don't work.
No logs are left on the server, so log information cannot be uploaded.

**Comment by xc1258** [comment]
NPCs files can be exported, but cannot be imported.
