### ISSUE TITLE
Missing sounds and skipping sounds

### ISSUE THREAD

**Issue by shanem82** [Suprcode/mir2#855]
upon further testing it would appear the sound problems are on certains spells and attacks i have uploaded a video with some text in it explaining at the time

in gernal all spells and actions seem slightly off while other sounds have a massive improment

http://www.slayzone.co.uk/LomSoundprob.mp4

**Comment by Lilcooldoode** [comment]
Have a look in your client side config file; MirSetup.ini I think it's called. Look for SoundOverLap=, maybe you have this set very low, try upping it to 10

**Comment by shanem82** [comment]
Tired that and even gone higher makes no difference the old sound system worked fine before and it's doing on every pc I have and all my friends pcs too

 I've even downloaded the source recompiled several times still no difference

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by MousaEqilan** [comment]
Yes, we are facing the same problem with skills etc... and it was initially working well before the big NET7 update

**Comment by shanem82** [comment]
has there been any news on this being looked or fixed maybe we should go back to the orignal sound system as it worked with no problems
