### ISSUE TITLE
Login Welcome Typo Error 

### ISSUE THREAD

**Issue by NoLife666** [Suprcode/mir2#890]
welcome message as you log in has a typo as seen in photo below 
![log error](https://github.com/Suprcode/mir2/assets/151167249/a8317ece-85db-448c-9096-cade6360b6ff)

**Comment by Suprcode** [comment]
This is a config issue not code related. Take a look at your language.ini in the server folder. The welcome message should read

""Welcome to the {0} Server.""

**Comment by NoLife666** [comment]
sorted thank you far
