### ISSUE TITLE
Equip slot issue

### ISSUE THREAD

**Issue by damianday** [Suprcode/mir2#899]
You can equip any item into a slot if you circumvent client checks, again server doesn't do thorough check.

**Comment by brandc87** [comment]
Isn't this checked by 

`actor.CanEquipItem(temp, to)`

**Comment by Suprcode** [comment]
The "CanUseItem" already checks that mount items can only be used on mounts, fishing items on fishing rod - but there does need to be an extra check to ensure the item type must be a socket item when not a mount/fishing item. Under this bit here

if ((item.Info.IsFishingRod || item.Info.Type == ItemType.Mount) && temp.Info.Type == ItemType.Socket)
            {
                Enqueue(p);
                return;
            }
