### ISSUE TITLE
Regarding the database version, the server and client are attached for reference.

### ISSUE THREAD

**Issue by sddzrxh** [Suprcode/mir2#923]
Sorry to bother you,
1. How to change the database version to minimum 80 and maximum 130? In this way, various database versions can match export and import. Because there are many versions, some are 88, some are 108, and the highest database version here is already 125. If you can read 80-130 databases, then any database can match.
2. The Client has released too many files. I want to reduce the number of files released by the Client.
3. There are three files in \Data\Map, which greatly increases the size of the client. I hope to minimize the size of the client.
Attached below are the server and client versions, hoping to help you. The contents are all in Chinese, so you can translate them yourself.
The client file was too big, I pressed it into a package and couldn't upload it, so I changed it to subcontracting.

If necessary, I will help you translate the client into English on the basis of the existing version (although I don't know much about English) As for the source code, there is nothing i can do, because the source code author is not public.

Server：https://www.mediafire.com/file/9zxbtixik1f71kz/Mir2%25E6%259C%258D%25E5%258A%25A1%25E7%25AB%25AFServer.rar/file
Client：https://www.mediafire.com/file/5afiylgw1a29hvw/%25E5%25AE%25A2%25E6%2588%25B7%25E7%25AB%25AFClient.rar/file

**Comment by sddzrxh** [comment]
Uploading QQ视频20240302143647.mp4…

**Comment by sddzrxh** [comment]
https://github.com/Suprcode/mir2/assets/42303818/b81ddde5-e494-4fcb-ab83-81b7115086ba

**Comment by sddzrxh** [comment]
https://github.com/Suprcode/mir2/assets/42303818/29c36ffc-2141-4d87-a4d0-78cb96f32628

**Comment by sddzrxh** [comment]
https://github.com/Suprcode/mir2/assets/42303818/edce74a8-ddf8-4f1b-adc8-efcb46d0490d

BUG

**Comment by sddzrxh** [comment]
Reducing the number of Launcher released files is too much

![QQ图片20240302211447](https://github.com/Suprcode/mir2/assets/42303818/fba74249-50d2-4daa-a701-5921c1e183e2)
![QQ图片20240302211528](https://github.com/Suprcode/mir2/assets/42303818/b67a459d-c894-4a58-aab0-01d96a55d15b)

**Comment by sddzrxh** [comment]
We also have a database website that connects with South Korea. I wonder if it will be helpful to you.
https://www.mir2db.com/
![QQ图片20240302213006](https://github.com/Suprcode/mir2/assets/42303818/0e85b3ae-3ded-4d6f-9fce-c7fc3739430e)

**Comment by cosocc** [comment]
加个好友

**Comment by sddzrxh** [comment]
> 加个好友

？？？？

**Comment by JevLOMCN** [comment]
> We also have a database website that connects with South Korea. I wonder if it will be helpful to you. https://www.mir2db.com/ ![QQ图片20240302213006](https://private-user-images.githubusercontent.com/42303818/309476178-0e85b3ae-3ded-4d6f-9fce-c7fc3739430e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkzOTQxNTYsIm5iZiI6MTcwOTM5Mzg1NiwicGF0aCI6Ii80MjMwMzgxOC8zMDk0NzYxNzgtMGU4NWIzYWUtM2RlZC00ZDZmLTlmY2UtYzdmYzM3Mzk0MzBlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzAyVDE1MzczNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc1ZmY3ZjllMzhhY2FjOTRiNDBjM2ZmYzIwODY3ZDNmYjhkY2QwMDgxYTdlYmMyZDU4ZjU3NWEzY2RlODM1ODImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.7bkrnThceGrdPlBLYdj2znzXFIs9gwxQ81X0zekWjhM)

This website is useless to us, we've attempted to contact the owner to get no reply. 

You are more than welcome to use [Crystal WIKI](https://www.lomcn.net/wiki/index.php/Crystal)

**Comment by sddzrxh** [comment]
> 非常欢迎您使用 [Crystal WIKI](https://www.lomcn.net/wiki/index.php/Crystal)

Let's take a look at the version I posted. I hope to change the server reading from 107 to 130, so that both the minimum and maximum can be read. The version server I posted was created by one person using your source code, which has been modified for half a year, from localization to improving various functions, and is now close to all official functions. Unfortunately, he does not disclose the source code

**Comment by JevLOMCN** [comment]
> > 非常欢迎您使用 [Crystal WIKI](https://www.lomcn.net/wiki/index.php/Crystal)
> 
> Let's take a look at the version I posted. I hope to change the server reading from 107 to 130, so that both the minimum and maximum can be read. The version server I posted was created by one person using your source code, which has been modified for half a year, from localization to improving various functions, and is now close to all official functions. Unfortunately, he does not disclose the source code

Why use a set of server files when you don't have the source? just use this source and work from this [database](https://github.com/Suprcode/mir2-database/releases/tag/20.12.23)

**Comment by sddzrxh** [comment]
> > > 非常欢迎您使用 [Crystal WIKI](https://www.lomcn.net/wiki/index.php/Crystal)
Because he is very good at C#, and he has the most functions, so I used her. Because the database is too high to match, I don't know much about C#, so I have no choice. I hope you will get better and better and improve your functions as soon as possible.

**Comment by JevLOMCN** [comment]
> > > > 非常欢迎您使用 [Crystal WIKI](https://www.lomcn.net/wiki/index.php/Crystal)
> 
> Because he is very good at C#, and he has the most functions, so I used her. Because the database is too high to match, I don't know much about C#, so I have no choice. I hope you will get better and better and improve your functions as soon as possible.
> 
> 

Can you send me the server files and client so I can decompile it? See if I can get a working source for you.

Jevlomcn@gmail.com

**Comment by sddzrxh** [comment]
> > > > > 非常欢迎您使用 [Crystal WIKI](https://www.lomcn.net/wiki/index.php/Crystal)

Here it is, the server and the client. I sent you the first page, with many functions. The official functions are basically all there, and I have also equipped the client.

Server：https://www.mediafire.com/file/9zxbtixik1f71kz/Mir2%25E6%259C%258D%25E5%258A%25A1%25E7%25AB%25AFServer.rar/file
Client：https://www.mediafire.com/file/5afiylgw1a29hvw/%25E5%25AE%25A2%25E6%2588%25B7%25E7%25AB%25AFClient.rar/file

**Comment by sddzrxh** [comment]
> > > > > 非常欢迎您使用 [Crystal WIKI](https://www.lomcn.net/wiki/index.php/Crystal)
You said you couldn't download 123 disks before, but now I have changed to MediaFire and I still can't download them?

**Comment by JevLOMCN** [comment]
> > > > > > 非常欢迎您使用 [Crystal WIKI](https://www.lomcn.net/wiki/index.php/Crystal)
> > > > > > You said you couldn't download 123 disks before, but now I have changed to MediaFire and I still can't download them?

Downloading now, thank you for using mediafile :D

**Comment by JevLOMCN** [comment]
Okay I've decompiled the server, you wont be able to do anything really without the actual source. The fact the user is keeping the source private should tell you enough.

**Comment by sddzrxh** [comment]
There is no way, you can learn from the functions inside, which are the results of hundreds of people testing for half a year, and the bugs and functions have been fixed.

**Comment by Suprcode** [comment]
1. Thats not how database versions work. They're limited because thats the range the files support. As older code gets removed the lower database versions will stop working.
2. not a bug. the files aren't there for fun
3. if you don't want the map objects for all other versions you can delete these

for your trust merchant reports bug - you cannot buy your own item. It sounds like you are not using the latest source here. If you can replicate the bug with the latest source code please open a new ticket.
