### ISSUE TITLE
PlayerInfoForm

### ISSUE THREAD

**Issue by sddzrxh** [Suprcode/mir2#928]
Hello developer, may I ask which function your PlayerInfoForm is displayed in? After I started Legend of Mir Server, I didn't see anywhere where I could open PlayerInfoForm. Shouldn't it be in Legend of Mir Server---Account---AccountInfoForm---and then double-click the user ID to pop up PlayerInfoForm? I understand where this feature pops up.

**Comment by sddzrxh** [comment]
Many people here are currently modifying the UI
![QQ图片20240306092543](https://github.com/Suprcode/mir2/assets/42303818/d9a648ae-eeb1-462d-a993-d6403bf71c3f)

**Comment by Suprcode** [comment]
There is no character form. Player objects don't exist until they are logged in - and from there you can see them in the player tab

**Comment by sddzrxh** [comment]
> There is no character form. Player objects don't exist until they are logged in - and from there you can see them in the player tab


https://github.com/Suprcode/mir2/assets/42303818/e8e45cda-a5d9-498f-9383-5610dead1ce2
